<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="5.1 Metrisch skalierte Variablen | GESIS Methodenseminar 2020" />
<meta property="og:type" content="book" />


<meta property="og:description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020" />


<meta name="author" content="Andreas Filser" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020">

<title>5.1 Metrisch skalierte Variablen | GESIS Methodenseminar 2020</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#herzlich-willkommen">Herzlich Willkommen!</a></li>
<li class="has-sub"><a href="1-Stata1.html#Stata1"><span class="toc-section-number">1</span> Einstieg in Stata</a><ul>
<li><a href="1-1-taschenrechner.html#taschenrechner"><span class="toc-section-number">1.1</span> Taschenrechner</a></li>
<li><a href="1-2-darstellung-in-diesem-skript.html#darstellung-in-diesem-skript"><span class="toc-section-number">1.2</span> Darstellung in diesem Skript</a></li>
<li><a href="1-3-dofile-editor.html#dofile-editor"><span class="toc-section-number">1.3</span> DoFile Editor</a></li>
<li><a href="1-4-datensätze-laden.html#datensätze-laden"><span class="toc-section-number">1.4</span> Datensätze laden</a></li>
<li><a href="1-5-daten-codebücher-fragebogen.html#daten-codebücher-fragebogen"><span class="toc-section-number">1.5</span> Daten, Codebücher, Fragebogen</a></li>
<li class="has-sub"><a href="1-6-überblicksbefehle.html#überblicksbefehle"><span class="toc-section-number">1.6</span> Überblicksbefehle</a><ul>
<li><a href="1-6-überblicksbefehle.html#describe"><span class="toc-section-number">1.6.1</span> <code>describe</code></a></li>
<li><a href="1-6-überblicksbefehle.html#browse"><span class="toc-section-number">1.6.2</span> <code>browse</code></a></li>
<li><a href="1-6-überblicksbefehle.html#list"><span class="toc-section-number">1.6.3</span> <code>list</code></a></li>
<li><a href="1-6-überblicksbefehle.html#lookfor"><span class="toc-section-number">1.6.4</span> <code>lookfor</code></a></li>
</ul></li>
<li><a href="1-7-löschen.html#löschen"><span class="toc-section-number">1.7</span> löschen</a></li>
<li><a href="1-8-if-bedingung-nur-manche-zeilen-ansehen.html#if-bedingung---nur-manche-zeilen-ansehen"><span class="toc-section-number">1.8</span> if Bedingung - nur manche Zeilen ansehen</a></li>
<li><a href="1-9-U1.html#U1"><span class="toc-section-number">1.9</span> Übungen 1</a></li>
<li><a href="1-10-profi-übungen-1.html#profi-übungen-1"><span class="toc-section-number">1.10</span> Profi-Übungen 1</a></li>
<li class="has-sub"><a href="1-11-anhang-1.html#anhang-1"><span class="toc-section-number">1.11</span> Anhang 1</a><ul>
<li><a href="1-11-anhang-1.html#var_types"><span class="toc-section-number">1.11.1</span> Variablentypen</a></li>
<li><a href="1-11-anhang-1.html#otherfmts"><span class="toc-section-number">1.11.2</span> import anderer Dateiformate</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="2-Stata2.html#Stata2"><span class="toc-section-number">2</span> Arbeiten mit Datensätzen in Stata</a><ul>
<li><a href="2-1-vorab-befehlsstruktur-hilfe.html#vorab-befehlsstruktur-hilfe"><span class="toc-section-number">2.1</span> Vorab: Befehlsstruktur &amp; Hilfe</a></li>
<li><a href="2-2-auszählen-überblick-erhalten.html#auszählen-überblick-erhalten"><span class="toc-section-number">2.2</span> Auszählen &amp; Überblick erhalten</a></li>
<li><a href="2-3-neue-variablen-erstellen.html#neue-variablen-erstellen"><span class="toc-section-number">2.3</span> Neue Variablen erstellen</a></li>
<li><a href="2-4-bestehende-variablen-verändern.html#bestehende-variablen-verändern"><span class="toc-section-number">2.4</span> Bestehende Variablen verändern</a></li>
<li><a href="2-5-gen-ist-gut-kontrolle-ist-besser.html#gen-ist-gut-kontrolle-ist-besser"><span class="toc-section-number">2.5</span> gen ist gut, Kontrolle ist besser</a></li>
<li><a href="2-6-fehlende-werte.html#fehlende-werte"><span class="toc-section-number">2.6</span> Fehlende Werte</a></li>
<li><a href="2-7-if-bedingungen-und-fehlende-werte.html#if-bedingungen-und-fehlende-werte"><span class="toc-section-number">2.7</span> if Bedingungen und fehlende Werte</a></li>
<li><a href="2-8-keep-drop.html#keep-drop"><span class="toc-section-number">2.8</span> keep &amp; drop</a></li>
<li><a href="2-9-labels-und-if-bedingungen.html#labels-und-if-bedingungen"><span class="toc-section-number">2.9</span> Labels und if-Bedingungen</a></li>
<li><a href="2-10-nochmal-von-vorne-daten-neu-laden.html#nochmal-von-vorne-daten-neu-laden"><span class="toc-section-number">2.10</span> Nochmal von vorne: Daten neu laden</a></li>
<li><a href="2-11-speichern.html#speichern"><span class="toc-section-number">2.11</span> Speichern</a></li>
<li><a href="2-12-übungen-2.html#übungen-2"><span class="toc-section-number">2.12</span> Übungen 2</a></li>
<li><a href="2-13-profi-übungen-2.html#profi-übungen-2"><span class="toc-section-number">2.13</span> Profi-Übungen 2</a></li>
</ul></li>
<li class="has-sub"><a href="3-desc1.html#desc1"><span class="toc-section-number">3</span> Deskriptive Statistik</a><ul>
<li class="has-sub"><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#kategoriale-merkmale-mit-tabulate-beschreiben"><span class="toc-section-number">3.1</span> Kategoriale Merkmale mit <code>tabulate</code> beschreiben</a><ul>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#zwei-variablen-eine-tabelle-kontingenztabellen"><span class="toc-section-number">3.1.1</span> Zwei Variablen, eine Tabelle: Kontingenztabellen</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#in-prozent-relative-häufigkeiten"><span class="toc-section-number">3.1.2</span> In Prozent: Relative Häufigkeiten</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-1-zeilenprozente"><span class="toc-section-number">3.1.3</span> pro Gruppe 1: Zeilenprozente</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-2-spaltenprozente"><span class="toc-section-number">3.1.4</span> pro Gruppe 2: Spaltenprozente</a></li>
</ul></li>
<li class="has-sub"><a href="3-2-metrische-variablen-beschreiben.html#metrische-variablen-beschreiben"><span class="toc-section-number">3.2</span> Metrische Variablen beschreiben</a><ul>
<li><a href="3-2-metrische-variablen-beschreiben.html#summarize"><span class="toc-section-number">3.2.1</span> <code>summarize</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#tabstat"><span class="toc-section-number">3.2.2</span> <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#by_vgl"><span class="toc-section-number">3.2.3</span> Kennzahlen vergleichen mit <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#streu"><span class="toc-section-number">3.2.4</span> Streuungsmaße: Varianz, Standardabweichung, Variationskoeffizient</a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#gini-koeffizient"><span class="toc-section-number">3.2.5</span> Gini-Koeffizient</a></li>
</ul></li>
<li class="has-sub"><a href="3-3-übungen-3.html#übungen-3"><span class="toc-section-number">3.3</span> Übungen 3</a><ul>
<li><a href="3-3-übungen-3.html#tab"><span class="toc-section-number">3.3.1</span> Übung 3-1</a></li>
<li><a href="3-3-übungen-3.html#met"><span class="toc-section-number">3.3.2</span> Übung 3-2</a></li>
<li><a href="3-3-übungen-3.html#weitere-übungen-3"><span class="toc-section-number">3.3.3</span> Weitere Übungen 3</a></li>
</ul></li>
<li><a href="3-4-profi-übungen-3.html#profi-übungen-3"><span class="toc-section-number">3.4</span> Profi-Übungen 3</a></li>
<li class="has-sub"><a href="3-5-anhang-kap-3.html#anhang-kap-3"><span class="toc-section-number">3.5</span> Anhang Kap 3</a><ul>
<li><a href="3-5-anhang-kap-3.html#vlabel"><span class="toc-section-number">3.5.1</span> labels vergeben</a></li>
<li><a href="3-5-anhang-kap-3.html#variance"><span class="toc-section-number">3.5.2</span> Varianz erklärt</a></li>
<li><a href="3-5-anhang-kap-3.html#sk_kur"><span class="toc-section-number">3.5.3</span> Schiefe &amp; Wölbung</a></li>
<li><a href="3-5-anhang-kap-3.html#bys_su"><span class="toc-section-number">3.5.4</span> Kombination von <code>summarize</code> mit dem <code>by</code>-Präfix</a></li>
<li><a href="3-5-anhang-kap-3.html#if_vgl"><span class="toc-section-number">3.5.5</span> Kennzahlvergleiche mit <code>if</code></a></li>
<li><a href="3-5-anhang-kap-3.html#kennzahlvergleich-mit-tabulate-und-der-option-summarize"><span class="toc-section-number">3.5.6</span> Kennzahlvergleich mit <code>tabulate</code> und der Option <code>summarize()</code></a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="4-dataviz.html#dataviz"><span class="toc-section-number">4</span> Datenvisualisierung in Stata</a><ul>
<li class="has-sub"><a href="4-1-visualisierung-einer-variable.html#visualisierung-einer-variable"><span class="toc-section-number">4.1</span> Visualisierung einer Variable</a><ul>
<li><a href="4-1-visualisierung-einer-variable.html#metrische-variablen"><span class="toc-section-number">4.1.1</span> metrische Variablen</a></li>
<li><a href="4-1-visualisierung-einer-variable.html#bar_col"><span class="toc-section-number">4.1.2</span> Kategoriale Variablen</a></li>
</ul></li>
<li><a href="4-2-verteilungen-vergleichen-mit-facetten.html#verteilungen-vergleichen-mit-facetten"><span class="toc-section-number">4.2</span> Verteilungen vergleichen mit Facetten</a></li>
<li class="has-sub"><a href="4-3-bivar-plot.html#bivar_plot"><span class="toc-section-number">4.3</span> Gemeinsame Verteilung zweier Variablen</a><ul>
<li><a href="4-3-bivar-plot.html#mosaikplot"><span class="toc-section-number">4.3.1</span> Mosaikplot</a></li>
<li><a href="4-3-bivar-plot.html#streudiagramm"><span class="toc-section-number">4.3.2</span> Streudiagramm</a></li>
</ul></li>
<li><a href="4-4-weitere-twoway-grafiken.html#weitere-twoway-grafiken"><span class="toc-section-number">4.4</span> Weitere <code>twoway</code> Grafiken</a></li>
<li><a href="4-5-twoway-comb.html#twoway_comb"><span class="toc-section-number">4.5</span> Kombinieren von zwei twoway-Grafiken</a></li>
<li><a href="4-6-gruppierte-boxplots.html#gruppierte-boxplots"><span class="toc-section-number">4.6</span> Gruppierte Boxplots</a></li>
<li class="has-sub"><a href="4-7-übungen-4.html#übungen-4"><span class="toc-section-number">4.7</span> Übungen 4</a><ul>
<li><a href="4-7-übungen-4.html#plt1"><span class="toc-section-number">4.7.1</span> Übung 4-1</a></li>
<li><a href="4-7-übungen-4.html#plt2"><span class="toc-section-number">4.7.2</span> Übung 4-2</a></li>
<li><a href="4-7-übungen-4.html#weitere-übungen-kap4"><span class="toc-section-number">4.7.3</span> Weitere Übungen Kap4</a></li>
</ul></li>
<li class="has-sub"><a href="4-8-optionen.html#optionen"><span class="toc-section-number">4.8</span> Optionen</a><ul>
<li><a href="4-8-optionen.html#title"><span class="toc-section-number">4.8.1</span> Titel</a></li>
<li><a href="4-8-optionen.html#achsenbeschriftung"><span class="toc-section-number">4.8.2</span> Achsenbeschriftung</a></li>
<li><a href="4-8-optionen.html#text-einfügen"><span class="toc-section-number">4.8.3</span> Text einfügen</a></li>
<li><a href="4-8-optionen.html#font"><span class="toc-section-number">4.8.4</span> Schriftart &amp; Textgröße</a></li>
<li><a href="4-8-optionen.html#legend"><span class="toc-section-number">4.8.5</span> Legende</a></li>
<li><a href="4-8-optionen.html#mark"><span class="toc-section-number">4.8.6</span> Marker</a></li>
<li><a href="4-8-optionen.html#color"><span class="toc-section-number">4.8.7</span> Farben</a></li>
<li><a href="4-8-optionen.html#vorlagen"><span class="toc-section-number">4.8.8</span> Vorlagen</a></li>
</ul></li>
<li class="has-sub"><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#anhang-beispiele-zum-selbst-anpassen"><span class="toc-section-number">4.9</span> Anhang &amp; Beispiele zum selbst anpassen</a><ul>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#boxplot"><span class="toc-section-number">4.9.1</span> Boxplot</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#scatterplot"><span class="toc-section-number">4.9.2</span> Scatterplot</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#pyramid"><span class="toc-section-number">4.9.3</span> Bevölkerungspyramide</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#boxplot1"><span class="toc-section-number">4.9.4</span> Boxplot</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="5-zshg.html#zshg"><span class="toc-section-number">5</span> Zusammenhangsmaße</a><ul>
<li class="has-sub"><a href="5-1-zshg-met.html#zshg_met"><span class="toc-section-number">5.1</span> Metrisch skalierte Variablen</a><ul>
<li><a href="5-1-zshg-met.html#cor"><span class="toc-section-number">5.1.1</span> Korrelationskoeffizient</a></li>
<li><a href="5-1-zshg-met.html#regression"><span class="toc-section-number">5.1.2</span> Regression</a></li>
<li><a href="5-1-zshg-met.html#vorhergesagte-werte"><span class="toc-section-number">5.1.3</span> vorhergesagte Werte</a></li>
</ul></li>
<li class="has-sub"><a href="5-2-zshg-ord.html#zshg_ord"><span class="toc-section-number">5.2</span> Ordinal skalierte Merkmale</a><ul>
<li><a href="5-2-zshg-ord.html#spear"><span class="toc-section-number">5.2.1</span> Spearman- Rangkorrelation</a></li>
<li><a href="5-2-zshg-ord.html#tau"><span class="toc-section-number">5.2.2</span> Konkordanzmaße</a></li>
</ul></li>
<li class="has-sub"><a href="5-3-zshg-nom.html#zshg_nom"><span class="toc-section-number">5.3</span> Nominal skalierte Variablen</a><ul>
<li><a href="5-3-zshg-nom.html#OR"><span class="toc-section-number">5.3.1</span> Odds Ratio</a></li>
<li><a href="5-3-zshg-nom.html#chi2"><span class="toc-section-number">5.3.2</span> Chi²-basierte Maße</a></li>
<li><a href="5-3-zshg-nom.html#cramers-upsilon"><span class="toc-section-number">5.3.3</span> Cramer’s <span class="math inline">\(\upsilon\)</span></a></li>
<li><a href="5-3-zshg-nom.html#phi"><span class="toc-section-number">5.3.4</span> <span class="math inline">\(\phi\)</span></a></li>
</ul></li>
<li><a href="5-4-welches-maß-richtig.html#welches-maß-richtig"><span class="toc-section-number">5.4</span> Welches Maß richtig?</a></li>
<li class="has-sub"><a href="5-5-übungen-5.html#übungen-5"><span class="toc-section-number">5.5</span> Übungen 5</a><ul>
<li><a href="5-5-übungen-5.html#auf_met"><span class="toc-section-number">5.5.1</span> Übung 5-1</a></li>
<li><a href="5-5-übungen-5.html#auf_ord"><span class="toc-section-number">5.5.2</span> Übung 5-2</a></li>
<li><a href="5-5-übungen-5.html#auf_nom"><span class="toc-section-number">5.5.3</span> Übung 5-3</a></li>
<li><a href="5-5-übungen-5.html#weitere-übungen-5"><span class="toc-section-number">5.5.4</span> Weitere Übungen 5</a></li>
</ul></li>
<li><a href="5-6-profi-übungen-5.html#profi-übungen-5"><span class="toc-section-number">5.6</span> Profi-Übungen 5</a></li>
<li class="has-sub"><a href="5-7-anhang.html#anhang"><span class="toc-section-number">5.7</span> Anhang</a><ul>
<li><a href="5-7-anhang.html#reg"><span class="toc-section-number">5.7.1</span> Idee einer Regression</a></li>
<li><a href="5-7-anhang.html#resid"><span class="toc-section-number">5.7.2</span> Residuen</a></li>
<li><a href="5-7-anhang.html#quad_res"><span class="toc-section-number">5.7.3</span> Quadrierte Residuen</a></li>
<li><a href="5-7-anhang.html#interpretation-der-regression"><span class="toc-section-number">5.7.4</span> Interpretation der Regression</a></li>
<li><a href="5-7-anhang.html#reg_pred"><span class="toc-section-number">5.7.5</span> Vorhergesagte Werte</a></li>
<li><a href="5-7-anhang.html#resid2"><span class="toc-section-number">5.7.6</span> Residuen Teil 2</a></li>
<li><a href="5-7-anhang.html#r2"><span class="toc-section-number">5.7.7</span> Modellgüte</a></li>
<li><a href="5-7-anhang.html#indiff"><span class="toc-section-number">5.7.8</span> Indifferenztabelle</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="6-zshg2.html#zshg2"><span class="toc-section-number">6</span> Zusammenhänge 2</a><ul>
<li><a href="6-1-zusammenhänge-vergleichen.html#zusammenhänge-vergleichen"><span class="toc-section-number">6.1</span> Zusammenhänge vergleichen</a></li>
<li><a href="6-2-zusammenhänge-visualisieren.html#zusammenhänge-visualisieren"><span class="toc-section-number">6.2</span> Zusammenhänge visualisieren</a></li>
<li class="has-sub"><a href="6-3-kategoriale-zusammenhänge.html#kategoriale-zusammenhänge"><span class="toc-section-number">6.3</span> Kategoriale Zusammenhänge</a><ul>
<li><a href="6-3-kategoriale-zusammenhänge.html#ordinale-zusammenhangsmaße-vergleichen"><span class="toc-section-number">6.3.1</span> Ordinale Zusammenhangsmaße vergleichen</a></li>
<li><a href="6-3-kategoriale-zusammenhänge.html#vergleich-visualisieren"><span class="toc-section-number">6.3.2</span> Vergleich visualisieren</a></li>
<li><a href="6-3-kategoriale-zusammenhänge.html#nominale-zusammenhangsmaße-vergleichen"><span class="toc-section-number">6.3.3</span> Nominale Zusammenhangsmaße vergleichen</a></li>
</ul></li>
<li class="has-sub"><a href="6-4-übungen-6.html#übungen-6"><span class="toc-section-number">6.4</span> Übungen 6</a><ul>
<li><a href="6-4-übungen-6.html#met_vgl"><span class="toc-section-number">6.4.1</span> Übung 6-1</a></li>
<li><a href="6-4-übungen-6.html#ord_vgl"><span class="toc-section-number">6.4.2</span> Übung 6-2</a></li>
<li><a href="6-4-übungen-6.html#nom_vgl"><span class="toc-section-number">6.4.3</span> Übung 6-3</a></li>
<li><a href="6-4-übungen-6.html#weitere-übungen-kap-6"><span class="toc-section-number">6.4.4</span> Weitere Übungen Kap 6</a></li>
</ul></li>
<li class="has-sub"><a href="5-7-anhang.html#anhang"><span class="toc-section-number">6.5</span> Anhang</a><ul>
<li><a href="6-5-anhang.html#lpattern"><span class="toc-section-number">6.5.1</span> Optionen für <code>lpattern</code></a></li>
<li><a href="6-5-anhang.html#scatterplot-für-kategoriale-merkmale"><span class="toc-section-number">6.5.2</span> Scatterplot für kategoriale Merkmale</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="7-inf1.html#inf1"><span class="toc-section-number">7</span> Inferenzstatistik I</a><ul>
<li><a href="7-1-inferenz.html#inferenz"><span class="toc-section-number">7.1</span> Inferenz</a></li>
<li class="has-sub"><a href="7-2-parametrische-ki-schätzung.html#parametrische-ki-schätzung"><span class="toc-section-number">7.2</span> Parametrische KI-Schätzung</a><ul>
<li><a href="7-2-parametrische-ki-schätzung.html#t-z-wert"><span class="toc-section-number">7.2.1</span> t-/z-Wert</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#standardfehler"><span class="toc-section-number">7.2.2</span> Standardfehler</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#kis-berechnen"><span class="toc-section-number">7.2.3</span> KIs berechnen</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#mean"><span class="toc-section-number">7.2.4</span> <code>mean</code></a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#vergleich"><span class="toc-section-number">7.2.5</span> Vergleich</a></li>
</ul></li>
<li><a href="7-3-bootstrapping.html#bootstrapping"><span class="toc-section-number">7.3</span> Bootstrapping</a></li>
<li><a href="7-4-übungen-7.html#übungen-7"><span class="toc-section-number">7.4</span> Übungen 7</a></li>
<li class="has-sub"><a href="7-5-anhang-kap7.html#anhang-kap7"><span class="toc-section-number">7.5</span> Anhang Kap7</a><ul>
<li><a href="7-5-anhang-kap7.html#normalverteilung"><span class="toc-section-number">7.5.1</span> Normalverteilung</a></li>
<li><a href="7-5-anhang-kap7.html#student-t-verteilung"><span class="toc-section-number">7.5.2</span> Student t-Verteilung</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="8-inf2.html#inf2"><span class="toc-section-number">8</span> t-Tests</a><ul>
<li><a href="8-1-hypothesentests.html#hypothesentests"><span class="toc-section-number">8.1</span> Hypothesentests</a></li>
<li class="has-sub"><a href="8-2-t-test.html#t-test"><span class="toc-section-number">8.2</span> t-Test</a><ul>
<li><a href="8-2-t-test.html#beiseitiger-t-test"><span class="toc-section-number">8.2.1</span> beiseitiger t-Test</a></li>
<li><a href="8-2-t-test.html#linksseitiger-t-test"><span class="toc-section-number">8.2.2</span> linksseitiger t-Test</a></li>
<li><a href="8-2-t-test.html#rechtsseitiger-t-test"><span class="toc-section-number">8.2.3</span> rechtsseitiger t-Test</a></li>
</ul></li>
<li><a href="8-3-übungen-8.html#übungen-8"><span class="toc-section-number">8.3</span> Übungen 8</a></li>
<li><a href="8-4-profi-übungen-8.html#profi-übungen-8"><span class="toc-section-number">8.4</span> Profi-Übungen 8</a></li>
<li class="has-sub"><a href="8-5-hinweise.html#hinweise"><span class="toc-section-number">8.5</span> Hinweise</a><ul>
<li><a href="8-5-hinweise.html#auswahl-der-in-vollzeit-beschäftigten-befragten"><span class="toc-section-number">8.5.1</span> Auswahl der in Vollzeit beschäftigten Befragten</a></li>
</ul></li>
</ul></li>
<li><a href="9-hypo.html#hypo"><span class="toc-section-number">9</span> Hypothesentests</a></li>
<li><a href="10-export1.html#export1"><span class="toc-section-number">10</span> Ergebnisexport &amp; weitere Tipps</a></li>
<li class="has-sub"><a href="11-adva.html#adva"><span class="toc-section-number">11</span> Fortgeschrittene Themen</a><ul>
<li><a href="11-1-wertelabels.html#wertelabels"><span class="toc-section-number">11.1</span> Wertelabels</a></li>
<li><a href="11-2-sortieren.html#sortieren"><span class="toc-section-number">11.2</span> sortieren</a></li>
<li><a href="11-3-informationen-aus-mehreren-variablen.html#informationen-aus-mehreren-variablen"><span class="toc-section-number">11.3</span> Informationen aus mehreren Variablen</a></li>
<li><a href="11-4-egen.html#egen"><span class="toc-section-number">11.4</span> egen</a></li>
<li><a href="11-5-gruppierte-berechnungen.html#gruppierte-berechnungen"><span class="toc-section-number">11.5</span> gruppierte Berechnungen</a></li>
<li><a href="11-6-sep1.html#sep1"><span class="toc-section-number">11.6</span> Subgruppen-Variablen erstellen mit <code>separate</code></a></li>
<li><a href="11-7-collapse.html#collapse"><span class="toc-section-number">11.7</span> collapse</a></li>
<li><a href="11-8-indikatoren-umdrehen.html#indikatoren-umdrehen"><span class="toc-section-number">11.8</span> Indikatoren umdrehen</a></li>
<li><a href="11-9-informationen-aus-mehreren-datensätzen.html#informationen-aus-mehreren-datensätzen"><span class="toc-section-number">11.9</span> Informationen aus mehreren Datensätzen</a></li>
<li><a href="11-10-arbeiten-mit-textvariablen.html#arbeiten-mit-textvariablen"><span class="toc-section-number">11.10</span> Arbeiten mit Textvariablen</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="zshg_met" class="section level2">
<h2><span class="header-section-number">5.1</span> Metrisch skalierte Variablen</h2>
<p>Wir sehen uns den (möglichen) Zusammenhang zwischen dem Alter (<code>age</code>) und dem BMI (<code>hs18</code>) der Befragten an. Dazu schließen wir zunächst die Missings aus und wählen die Befragten aus dem Jahr 2012 aus:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb202-1"><a href="5-1-zshg-met.html#cb202-1"></a>cd <span class="st">&quot;&quot;</span></span>
<span id="cb202-2"><a href="5-1-zshg-met.html#cb202-2"></a><span class="kw">use</span>  Allbus_1980-2018.dta   </span>
<span id="cb202-3"><a href="5-1-zshg-met.html#cb202-3"></a><span class="kw">keep</span> <span class="kw">if</span> <span class="fu">year</span> == 2012</span>
<span id="cb202-4"><a href="5-1-zshg-met.html#cb202-4"></a><span class="kw">mvdecode</span> age hs18, mv(-32 -13)</span></code></pre></div>
<pre><code>##  . qui cd &quot;D:\Studium\01_Oldenburg\Lehre\Datensaetze&quot;
## 
## . qui use  &quot;Allbus_1980-2018.dta&quot;,clear
## 
## . keep if year == 2012
## (64681 observations deleted)
## 
## . mvdecode age hs18, mv(-32 -13)
##          age: 7 missing values generated
##         hs18: 1859 missing values generated</code></pre>
<div id="cor" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Korrelationskoeffizient</h3>
<p>Zur Bestimmung eines Zusammenhangs zwischen zwei metrischen Variablen empfiehlt sich der Korrelationskoeffizient nach Pearson. Dieser ist definiert als die Kovarianz dividiert durch die jeweiligen Standardabweichungen der beiden Variablen und liegt im Intervall [-1,1]. Die Standardabweichung hatten wir in Session 4 kennengelernt, die Kovarianz erfasst die Lage der Datenpunkte relativ zu den Mittelwerten der beiden interessierenden Variablen (liegen Punkte &gt; <span class="math inline">\(\bar{x}\)</span> auch <span class="math inline">\(&gt;\bar{y}\)</span>?):</p>
<p><img src="Stata_Skript_files/figure-html/s07_15b-1.png" width="80%" height="80%" style="display: block; margin: auto;" />
In Stata können wir den Korrelationskoeffizienten mit <code>corr</code> berechnen:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb204-1"><a href="5-1-zshg-met.html#cb204-1"></a><span class="fu">corr</span> age hs18</span></code></pre></div>
<pre><code>##  . set linesize 90
## 
## . qui cd &quot;D:\Studium\01_Oldenburg\Lehre\Datensaetze&quot;
## 
## . qui use  &quot;Allbus_1980-2018.dta&quot;,clear
## 
## . qui keep if year == 2012
## 
## . qui mvdecode age hs18, mv(-32 -13)
## 
## . corr age hs18
## (obs=1620)
## 
##              |      age     hs18
## -------------+------------------
##          age |   1.0000
##         hs18 |   0.2127   1.0000</code></pre>
<p>Es handelt sich also um einen geringen Zusammenhang.</p>
</div>
<div id="regression" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Regression</h3>
<p>Regressionsmodelle zeigen uns den (linearen) Trend zwischen zwei Variablen. Hier geht es darum, um wie sich im Durchschnitt <code>var2</code> verändert, wenn sich <code>var1</code> um eine Einheit erhöht. <code>var2</code> ist also unsere abhängige, <code>var1</code> unsere unabhängige Variable - wir möchten <code>var2</code> mit <code>var1</code> vorhersagen. Im Folgenden sehen wir, dass Regressionsmodelle mit <code>reg</code> erstellt werden können und wie wir den Output interpretieren können. Falls Sie nochmal mehr zu den Grundlagen erfahren wollten, findet sich <a href="5-7-anhang.html#reg">hier</a> eine ausführlichere Erklärung.</p>
<p>Wir betrachten einen kleinen Beispieldatensatz mit lediglich 4 Fällen und zwei metrischen Variablen <code>var1</code> und <code>var2</code>:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb206-1"><a href="5-1-zshg-met.html#cb206-1"></a><span class="kw">use</span> <span class="st">&quot;https://github.com/filius23/Stata_Skript/raw/master/regression_bsp.dta&quot;</span>, <span class="kw">clear</span></span></code></pre></div>
<p><img src="Stata_Skript_files/figure-html/regp1-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Mit Regressionsmodellen können wir lineare Zusammenhänge zwischen zwei metrischen Merkmalen untersuchen. In Stata können wir eine Regression mit dem <code>reg</code> Befehl berechnen:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb207-1"><a href="5-1-zshg-met.html#cb207-1"></a><span class="kw">reg</span> var2 var1</span></code></pre></div>
<pre><code>##  . use &quot;regression_bsp.dta&quot;, clear
## 
## . egen mean_var2 = mean(var2)
## 
## . gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . predict pred_vorher, xb
## 
## . gen res = var2 - pred_vorher 
## 
## . gen res2 = res^2
## 
## . set linesize 90
## 
## . reg var2 var1
## 
##       Source |       SS       df       MS              Number of obs =       4
## -------------+------------------------------           F(  1,     2) =   11.07
##        Model |  12.4932432     1  12.4932432           Prob &gt; F      =  0.0797
##     Residual |  2.25675676     2  1.12837838           R-squared     =  0.8470
## -------------+------------------------------           Adj R-squared =  0.7705
##        Total |       14.75     3  4.91666667           Root MSE      =  1.0623
## 
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------</code></pre>
<p>Hier steht jetzt eine ganze Menge an Informationen, die wir uns im Folgenden genauer ansehen werden.</p>
<hr />
<p>Ein positiver Wert unter <code>Coef.</code> in der Zeile von <code>var1</code> bedeutet, dass unsere Gerade von links nach rechts ansteigt und ein negativer eine fallende Linie bedeuten würde. Der Wert unter <code>var1</code> gibt an, um <em>wieviel sich die Gerade pro “Schritt nach rechts” nach oben/unten verändert</em>.</p>
<blockquote>
<p>Die Gerade steigt also pro Einheit von <code>var1</code> um 0.5810811.</p>
</blockquote>
<p>Der Wert neben <code>_cons</code> gibt uns Auskunft darüber, wie hoch der vorhergesagte Wert für <code>var2</code> wäre, wenn <code>var1</code> = 0.</p>
<blockquote>
<p>Für <code>var1</code> = 0 würden wir <code>var2</code> = 2.135135 vorhersagen.</p>
</blockquote>
<p>Außerdem erkennen wir unter <code>R-squared</code> die <a href="5-7-anhang.html#r2">Modellgüte</a> unseres Regressionsmodells. <span class="math inline">\(R^2\)</span> gibt die prozentuale Verbesserung der Vorhersgen durch die Gerade aus <code>reg</code> im Vergleich zum arithmetische Mittel an. <span class="math inline">\(R^{2}\)</span> bezieht sich auf die Verringerung der <a href="5-7-anhang.html#resid2">Residuen</a> durch das <code>reg</code>-Modell im Vergleich zur Mittelwertregel.</p>
<blockquote>
<p>Unser Regressionsmodell kann also 84,7% der Streuung um den Mittelwert erklären.</p>
</blockquote>
<p>Außerdem sehen wir oben links in der Spalte <code>SS</code> die <a href="5-7-anhang.html#quad_res">“Sum of Squares”</a>: unter <code>Total</code> ist die Summe der quadrierten Abweichungen der beobachteten Werte vom arith. Mittel angegeben (die Abstände zwischen den orangen und schwarzen Punkten: <code>14.75</code>). Residual gibt die Summe der Abweichungsquadrate zwischen den beobachteten Werten und den vorhergesagten Werten der Regression (die Abstände zwischen den schwarzen und den blauen Punkten:<code>2.256..</code>).</p>
<hr />
<p><img src="Stata_Skript_files/figure-html/reg_graph-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="vorhergesagte-werte" class="section level3">
<h3><span class="header-section-number">5.1.3</span> vorhergesagte Werte</h3>
<p>Die vorhergesagten Werte aus <code>reg var2 var1</code> entsprechen einfach der Summe aus dem Wert neben <code>_cons</code> und dem Koeffizienten neben <code>var1</code> multipliziert mit dem jeweiligen Wert für <code>var1</code>. Wir starten also sozusagen bei <code>var2</code>=0 und gehen dann eben x Schritte entlang der Geraden.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb209-1"><a href="5-1-zshg-met.html#cb209-1"></a><span class="kw">reg</span> var2 var1, <span class="kw">noheader</span> <span class="co">/// noheader macht den Output übersichtlicher</span></span></code></pre></div>
<pre><code>##  . use &quot;regression_bsp.dta&quot;, clear
## 
## . qui egen mean_var2 = mean(var2)
## 
## . qui gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . qui predict pred_vorher, xb
## 
## . qui gen res = var2 - pred_vorher 
## 
## . qui gen res2 = res^2
## 
## . qui set linesize 90
## 
## . reg var2 var1, noheader
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------</code></pre>
<p>Vorhergesagte Werte für <code>var2</code> werden mit <span class="math inline">\(\widehat{var2}\)</span> bezeichnet - das <span class="math inline">\(\widehat{}\)</span> steht dabei für “geschätzt”:</p>
<p><span class="math display">\[\widehat{var2}=\texttt{Intercept} + 0.5811 \times \texttt{var1}\]</span><br />
Für die erste Zeile ergibt sich also folgender vorhergesagter Wert: 2.1351+0.5811*1= 2.7162</p>
<p>Wir könnten also auch einen vorhergesagten Wert für einen beliebigen Wert von <code>var1</code> berechnen, für 5:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb211-1"><a href="5-1-zshg-met.html#cb211-1"></a><span class="kw">display</span> 2.1351+0.5811*5</span>
<span id="cb211-2"><a href="5-1-zshg-met.html#cb211-2"></a>##  . <span class="kw">display</span> 2.1351+0.5811*5</span>
<span id="cb211-3"><a href="5-1-zshg-met.html#cb211-3"></a>## 5.0406</span></code></pre></div>
<p>Alternativ können wir uns die Tipparbeit auch sparen, indem wir erst <code>reg</code> laufen lassen und dann mit <code>_b</code> auf die Ergebnisse zugreifen:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb212-1"><a href="5-1-zshg-met.html#cb212-1"></a><span class="kw">reg</span> var2 var1</span>
<span id="cb212-2"><a href="5-1-zshg-met.html#cb212-2"></a><span class="kw">display</span> _b[<span class="dt">_cons</span>] + _b[var1] * 5</span></code></pre></div>
<pre><code>##  . use &quot;regression_bsp.dta&quot;, clear
## 
## . qui reg var2 var1
## 
## . display _b[_cons] + _b[var1] * 5
## 5.0405405</code></pre>
<p>Mit <code>predict</code> können wir jeweils die vorhergesagten Werte für die Ausprägungen von <code>var1</code> im Datensatz berechnen und in einer neuen Variable <code>pred_vorher</code> ablegen:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb214-1"><a href="5-1-zshg-met.html#cb214-1"></a><span class="kw">predict</span> pred_vorher, <span class="kw">xb</span></span></code></pre></div>
<p>Hier wird also gerechnet:</p>
<p><span class="math display">\[2.1351 + 0.5810811 * 1 = 2.716216\]</span>
<span class="math display">\[2.1351 + 0.5810811 * 2 = 3.297297\]</span>
<span class="math display">\[2.1351 + 0.5810811 * 7 = 6.202703\]</span>
<span class="math display">\[2.1351 + 0.5810811 * 8 = 6.783784\]</span></p>
<pre><code>##   var1 var2 pred_vorher mean_var2
## 1    1    2    2.716216      4.75
## 2    2    4    3.297297      4.75
## 3    7    7    6.202703      4.75
## 4    8    6    6.783784      4.75</code></pre>
<p>Die Grafik oben zeigt wie Vorhersagen auf Basis des Regressionsmodells aussehen: Sie entsprechen den Werten auf der blauen Geraden (der sog. Regressionsgeraden) an den jeweiligen Stellen für <code>var1</code>.</p>
<hr />
<p><strong><a href="5-5-übungen-5.html#auf_met">Übung1</a></strong></p>
<hr />
</div>
</div>
<p style="text-align: center;">
<a href="5-zshg.html"><button class="btn btn-default">Previous</button></a>
<a href="5-2-zshg-ord.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
