<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="5.2 Regression | GESIS Methodenseminar 2020" />
<meta property="og:type" content="book" />


<meta property="og:description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020" />


<meta name="author" content="Andreas Filser" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020">

<title>5.2 Regression | GESIS Methodenseminar 2020</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#herzlich-willkommen">Herzlich Willkommen!</a></li>
<li class="has-sub"><a href="1-Stata1.html#Stata1"><span class="toc-section-number">1</span> Einstieg in Stata</a><ul>
<li><a href="1-1-taschenrechner.html#taschenrechner"><span class="toc-section-number">1.1</span> Taschenrechner</a></li>
<li><a href="1-2-darstellung-in-diesem-skript.html#darstellung-in-diesem-skript"><span class="toc-section-number">1.2</span> Darstellung in diesem Skript</a></li>
<li><a href="1-3-dofile-editor.html#dofile-editor"><span class="toc-section-number">1.3</span> DoFile Editor</a></li>
<li><a href="1-4-datensätze-laden.html#datensätze-laden"><span class="toc-section-number">1.4</span> Datensätze laden</a></li>
<li><a href="1-5-daten-codebücher-fragebogen.html#daten-codebücher-fragebogen"><span class="toc-section-number">1.5</span> Daten, Codebücher, Fragebogen</a></li>
<li class="has-sub"><a href="1-6-überblicksbefehle.html#überblicksbefehle"><span class="toc-section-number">1.6</span> Überblicksbefehle</a><ul>
<li><a href="1-6-überblicksbefehle.html#describe"><span class="toc-section-number">1.6.1</span> <code>describe</code></a></li>
<li><a href="1-6-überblicksbefehle.html#browse"><span class="toc-section-number">1.6.2</span> <code>browse</code></a></li>
<li><a href="1-6-überblicksbefehle.html#list"><span class="toc-section-number">1.6.3</span> <code>list</code></a></li>
<li><a href="1-6-überblicksbefehle.html#lookfor"><span class="toc-section-number">1.6.4</span> <code>lookfor</code></a></li>
</ul></li>
<li><a href="1-7-if-bedingung-nur-manche-zeilen-ansehen.html#if-bedingung---nur-manche-zeilen-ansehen"><span class="toc-section-number">1.7</span> if Bedingung - nur manche Zeilen ansehen</a></li>
<li><a href="1-8-U1.html#U1"><span class="toc-section-number">1.8</span> Übungen</a></li>
<li><a href="1-9-profi-übungen.html#profi-übungen"><span class="toc-section-number">1.9</span> Profi-Übungen</a></li>
<li class="has-sub"><a href="1-10-weitere-anmerkungen.html#weitere-anmerkungen"><span class="toc-section-number">1.10</span> Weitere Anmerkungen</a><ul>
<li><a href="1-10-weitere-anmerkungen.html#var_types"><span class="toc-section-number">1.10.1</span> Variablentypen</a></li>
<li><a href="1-10-weitere-anmerkungen.html#otherfmts"><span class="toc-section-number">1.10.2</span> import anderer Dateiformate</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="2-Stata2.html#Stata2"><span class="toc-section-number">2</span> Arbeiten mit Datensätzen in Stata</a><ul>
<li><a href="2-1-vorab-befehlsstruktur-hilfe.html#vorab-befehlsstruktur-hilfe"><span class="toc-section-number">2.1</span> Vorab: Befehlsstruktur &amp; Hilfe</a></li>
<li><a href="2-2-auszählen-überblick-erhalten.html#auszählen-überblick-erhalten"><span class="toc-section-number">2.2</span> Auszählen &amp; Überblick erhalten</a></li>
<li><a href="2-3-neue-variablen-erstellen.html#neue-variablen-erstellen"><span class="toc-section-number">2.3</span> Neue Variablen erstellen</a></li>
<li><a href="2-4-bestehende-variablen-verändern.html#bestehende-variablen-verändern"><span class="toc-section-number">2.4</span> Bestehende Variablen verändern</a></li>
<li><a href="2-5-gen-ist-gut-kontrolle-ist-besser.html#gen-ist-gut-kontrolle-ist-besser"><span class="toc-section-number">2.5</span> gen ist gut, Kontrolle ist besser</a></li>
<li><a href="2-6-fehlende-werte.html#fehlende-werte"><span class="toc-section-number">2.6</span> Fehlende Werte</a></li>
<li><a href="2-7-if-bedingungen-und-fehlende-werte.html#if-bedingungen-und-fehlende-werte"><span class="toc-section-number">2.7</span> if Bedingungen und fehlende Werte</a></li>
<li><a href="2-8-keep-drop.html#keep-drop"><span class="toc-section-number">2.8</span> keep &amp; drop</a></li>
<li><a href="2-9-labels-und-if-bedingungen.html#labels-und-if-bedingungen"><span class="toc-section-number">2.9</span> Labels und if-Bedingungen</a></li>
<li><a href="2-10-nochmal-von-vorne-daten-neu-laden.html#nochmal-von-vorne-daten-neu-laden"><span class="toc-section-number">2.10</span> Nochmal von vorne: Daten neu laden</a></li>
<li><a href="2-11-speichern.html#speichern"><span class="toc-section-number">2.11</span> Speichern</a></li>
<li><a href="2-12-übungen.html#übungen"><span class="toc-section-number">2.12</span> Übungen</a></li>
<li><a href="1-9-profi-übungen.html#profi-übungen"><span class="toc-section-number">2.13</span> Profi-Übungen</a></li>
</ul></li>
<li class="has-sub"><a href="3-desc1.html#desc1"><span class="toc-section-number">3</span> Deskriptive Statistik</a><ul>
<li class="has-sub"><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#kategoriale-merkmale-mit-tabulate-beschreiben"><span class="toc-section-number">3.1</span> Kategoriale Merkmale mit <code>tabulate</code> beschreiben</a><ul>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#zwei-variablen-eine-tabelle-kontingenztabellen"><span class="toc-section-number">3.1.1</span> Zwei Variablen, eine Tabelle: Kontingenztabellen</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#in-prozent-relative-häufigkeiten"><span class="toc-section-number">3.1.2</span> In Prozent: Relative Häufigkeiten</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-1-zeilenprozente"><span class="toc-section-number">3.1.3</span> pro Gruppe 1: Zeilenprozente</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-2-spaltenprozente"><span class="toc-section-number">3.1.4</span> pro Gruppe 2: Spaltenprozente</a></li>
</ul></li>
<li class="has-sub"><a href="3-2-metrische-variablen-beschreiben.html#metrische-variablen-beschreiben"><span class="toc-section-number">3.2</span> Metrische Variablen beschreiben</a><ul>
<li><a href="3-2-metrische-variablen-beschreiben.html#summarize"><span class="toc-section-number">3.2.1</span> <code>summarize</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#tabstat"><span class="toc-section-number">3.2.2</span> <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#by_vgl"><span class="toc-section-number">3.2.3</span> Kennzahlen vergleichen mit <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#tabulate-mit-der-option-summarize"><span class="toc-section-number">3.2.4</span> <code>tabulate</code> mit der Option <code>summarize()</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#variance"><span class="toc-section-number">3.2.5</span> Streuungsmaße: Varianz, Standardabweichung, Variationskoeffizient</a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#sk_kur"><span class="toc-section-number">3.2.6</span> Schiefe &amp; Wölbung</a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#gini-koeffizient"><span class="toc-section-number">3.2.7</span> Gini-Koeffizient</a></li>
</ul></li>
<li><a href="2-12-übungen.html#übungen"><span class="toc-section-number">3.3</span> Übungen</a></li>
<li><a href="1-9-profi-übungen.html#profi-übungen"><span class="toc-section-number">3.4</span> Profi-Übungen</a></li>
<li><a href="3-5-vlabel.html#vlabel"><span class="toc-section-number">3.5</span> Exkurs: labels vergeben</a></li>
<li><a href="3-6-bys-su.html#bys_su"><span class="toc-section-number">3.6</span> Exkurs: Kombination von <code>summarize</code> mit dem <code>by</code>-Präfix</a></li>
<li><a href="3-7-if-vgl.html#if_vgl"><span class="toc-section-number">3.7</span> Exkurs: Kennzahlvergleiche mit <code>if</code></a></li>
</ul></li>
<li class="has-sub"><a href="4-dataviz.html#dataviz"><span class="toc-section-number">4</span> Datenvisualisierung in Stata</a><ul>
<li><a href="4-1-erste-entscheidungen.html#erste-entscheidungen"><span class="toc-section-number">4.1</span> Erste Entscheidungen</a></li>
<li class="has-sub"><a href="4-2-grafik-syntax-in-stata.html#grafik-syntax-in-stata"><span class="toc-section-number">4.2</span> Grafik-Syntax in Stata</a><ul>
<li><a href="4-2-grafik-syntax-in-stata.html#aufbau"><span class="toc-section-number">4.2.1</span> Aufbau</a></li>
<li><a href="4-2-grafik-syntax-in-stata.html#twoway"><span class="toc-section-number">4.2.2</span> twoway</a></li>
<li><a href="4-2-grafik-syntax-in-stata.html#kombinieren-von-zwei-twoway-grafiken"><span class="toc-section-number">4.2.3</span> Kombinieren von zwei twoway-Grafiken</a></li>
<li><a href="4-2-grafik-syntax-in-stata.html#twoway-varianten"><span class="toc-section-number">4.2.4</span> twoway Varianten</a></li>
<li><a href="4-2-grafik-syntax-in-stata.html#vorlagen"><span class="toc-section-number">4.2.5</span> Vorlagen</a></li>
</ul></li>
<li class="has-sub"><a href="4-3-optionen.html#optionen"><span class="toc-section-number">4.3</span> Optionen</a><ul>
<li><a href="4-3-optionen.html#beschriftungen"><span class="toc-section-number">4.3.1</span> Beschriftungen</a></li>
<li><a href="4-3-optionen.html#farben"><span class="toc-section-number">4.3.2</span> Farben</a></li>
<li><a href="4-3-optionen.html#subgruppen"><span class="toc-section-number">4.3.3</span> Subgruppen</a></li>
</ul></li>
<li class="has-sub"><a href="4-4-beispiele-zum-selbst-anpassen.html#beispiele-zum-selbst-anpassen"><span class="toc-section-number">4.4</span> Beispiele zum selbst anpassen</a><ul>
<li><a href="4-4-beispiele-zum-selbst-anpassen.html#boxplot"><span class="toc-section-number">4.4.1</span> Boxplot</a></li>
</ul></li>
<li><a href="4-5-bevölkerungspyramide.html#bevölkerungspyramide"><span class="toc-section-number">4.5</span> Bevölkerungspyramide</a></li>
<li class="has-sub"><a href="4-6-anhang.html#anhang"><span class="toc-section-number">4.6</span> Anhang</a><ul>
<li><a href="4-6-anhang.html#aufb1"><span class="toc-section-number">4.6.1</span> Aufbereitung für Boxplot</a></li>
<li><a href="4-6-anhang.html#sep1"><span class="toc-section-number">4.6.2</span> <code>separate</code></a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="5-zshg.html#zshg"><span class="toc-section-number">5</span> Zusammenhangsmaße</a><ul>
<li><a href="5-1-metrisch-skalierte-variablen.html#metrisch-skalierte-variablen"><span class="toc-section-number">5.1</span> Metrisch skalierte Variablen</a></li>
<li class="has-sub"><a href="5-2-regression.html#regression"><span class="toc-section-number">5.2</span> Regression</a><ul>
<li><a href="5-2-regression.html#beispieldatensatz"><span class="toc-section-number">5.2.1</span> Beispieldatensatz</a></li>
<li><a href="5-2-regression.html#idee-einer-regression"><span class="toc-section-number">5.2.2</span> Idee einer Regression</a></li>
<li><a href="5-2-regression.html#residuen"><span class="toc-section-number">5.2.3</span> Residuen</a></li>
<li><a href="5-2-regression.html#quadrierte-residuen"><span class="toc-section-number">5.2.4</span> Quadrierte Residuen</a></li>
<li><a href="5-2-regression.html#interpretation-der-regression"><span class="toc-section-number">5.2.5</span> Interpretation der Regression</a></li>
<li><a href="5-2-regression.html#vorhergesagte-werte"><span class="toc-section-number">5.2.6</span> Vorhergesagte Werte</a></li>
<li><a href="5-2-regression.html#residuen-teil-2"><span class="toc-section-number">5.2.7</span> Residuen Teil 2</a></li>
<li><a href="5-2-regression.html#modellgüte"><span class="toc-section-number">5.2.8</span> Modellgüte</a></li>
</ul></li>
<li><a href="5-3-ordinal-skalierte-merkmale.html#ordinal-skalierte-merkmale"><span class="toc-section-number">5.3</span> Ordinal skalierte Merkmale</a></li>
<li class="has-sub"><a href="5-4-nominal-skalierte-variablen.html#nominal-skalierte-variablen"><span class="toc-section-number">5.4</span> Nominal skalierte Variablen</a><ul>
<li><a href="5-4-nominal-skalierte-variablen.html#odds-ratio"><span class="toc-section-number">5.4.1</span> Odds Ratio</a></li>
<li><a href="5-4-nominal-skalierte-variablen.html#chi²-basierte-maße"><span class="toc-section-number">5.4.2</span> Chi²-basierte Maße</a></li>
<li><a href="5-4-nominal-skalierte-variablen.html#cramers-upsilon"><span class="toc-section-number">5.4.3</span> Cramer’s <span class="math inline">\(\upsilon\)</span></a></li>
<li><a href="5-4-nominal-skalierte-variablen.html#indifferenztabelle"><span class="toc-section-number">5.4.4</span> Indifferenztabelle</a></li>
<li><a href="5-4-nominal-skalierte-variablen.html#phi"><span class="toc-section-number">5.4.5</span> <span class="math inline">\(\phi\)</span></a></li>
</ul></li>
</ul></li>
<li><a href="6-zshg2.html#zshg2"><span class="toc-section-number">6</span> Zusammenhänge 2</a></li>
<li><a href="7-inf1.html#inf1"><span class="toc-section-number">7</span> Inferenzstatistik I</a></li>
<li><a href="8-inf2.html#inf2"><span class="toc-section-number">8</span> Inferenzstatistik II</a></li>
<li><a href="9-hypo.html#hypo"><span class="toc-section-number">9</span> Hypothesentests</a></li>
<li><a href="10-export1.html#export1"><span class="toc-section-number">10</span> Ergebnisexport &amp; weitere Tipps</a></li>
<li class="has-sub"><a href="11-adva.html#adva"><span class="toc-section-number">11</span> Fortgeschrittene Themen</a><ul>
<li><a href="11-1-wertelabels.html#wertelabels"><span class="toc-section-number">11.1</span> Wertelabels</a></li>
<li><a href="11-2-sortieren.html#sortieren"><span class="toc-section-number">11.2</span> sortieren</a></li>
<li><a href="11-3-missings-unterscheiden.html#missings-unterscheiden"><span class="toc-section-number">11.3</span> missings unterscheiden</a></li>
<li><a href="11-4-indikatoren-umdrehen.html#indikatoren-umdrehen"><span class="toc-section-number">11.4</span> Indikatoren umdrehen</a></li>
<li><a href="11-5-informationen-aus-mehreren-variablen.html#informationen-aus-mehreren-variablen"><span class="toc-section-number">11.5</span> Informationen aus mehreren Variablen</a></li>
<li><a href="11-6-informationen-aus-mehreren-datensätzen.html#informationen-aus-mehreren-datensätzen"><span class="toc-section-number">11.6</span> Informationen aus mehreren Datensätzen</a></li>
<li><a href="11-7-arbeiten-mit-textvariablen.html#arbeiten-mit-textvariablen"><span class="toc-section-number">11.7</span> Arbeiten mit Textvariablen</a></li>
<li><a href="11-8-egen.html#egen"><span class="toc-section-number">11.8</span> egen</a></li>
<li><a href="11-9-gruppierte-berechnungen.html#gruppierte-berechnungen"><span class="toc-section-number">11.9</span> gruppierte Berechnungen</a></li>
<li><a href="11-10-collapse.html#collapse"><span class="toc-section-number">11.10</span> collapse</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="regression" class="section level2">
<h2><span class="header-section-number">5.2</span> Regression</h2>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-31-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Mit Regressionsmodellen können wir Zusammenhänge zwischen zwei metrischen Merkmalen untersuchen. In Stata können wir eine Regression mit dem <code>reg</code> Befehl berechnen:</p>
<pre><code>## 
## 
## . use &quot;regression_bsp.dta&quot;, cl. egen mean_var2 = mean(var2)
## 
## . gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . predict pred_vorher, xb
## 
## . gen res = var2 - pred_vorher 
## 
## . gen res2 = res^2
## 
## . set linesize 90
## 
## . reg var2 var1
## 
##       Source |       SS       df       MS              Number of obs =       4
## -------------+------------------------------           F(  1,     2) =   11.07
##        Model |  12.4932432     1  12.4932432           Prob &gt; F      =  0.0797
##     Residual |  2.25675676     2  1.12837838           R-squared     =  0.8470
## -------------+------------------------------           Adj R-squared =  0.7705
##        Total |       14.75     3  4.91666667           Root MSE      =  1.0623
## 
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------</code></pre>
<p>Hier steht jetzt eine ganze Menge an Informationen, die wir uns im Folgenden genauer ansehen werden.</p>
<div id="beispieldatensatz" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Beispieldatensatz</h3>
<p>Zum Einstieg betrachten wir zunächst einen (fiktiven) Datensatz mit lediglich 4 Fällen und lediglich zwei Variablen: <code>var1</code> und <code>var2</code>:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb185-1"><a href="5-2-regression.html#cb185-1"></a><span class="kw">use</span> <span class="st">&quot;https://github.com/filius23/Stata_Skript/raw/master/regression_bsp.dta&quot;</span>, <span class="kw">clear</span></span>
<span id="cb185-2"><a href="5-2-regression.html#cb185-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2
## 1    1    2
## 2    2    4
## 3    7    7
## 4    8    6</code></pre>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-35-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="idee-einer-regression" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Idee einer Regression</h3>
<p>Ziel der Regression ist es, den Zusammenhang zwischen diesen beiden Variablen zu bestimmen. Gibt es einen Trend, in dem Sinn, dass ein höherer Wert von <code>var1</code> mit einem höheren oder niedrigeren Wert von <code>var2</code> einhergeht?</p>
<p>Etwas anders gesagt könnte man auch fragen, welchen Wert für <code>var2</code> wir vorhersagen würden, wenn wir <code>var1</code> kennen. Ein Ausgangspunkt ist das arithmetische Mittel. Dieses können wir mit <code>mean</code> zB für <code>var2</code> berechnen.<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a> Diesen Wert fügen wir als neue Spalte <code>mean_var2</code> in den Datensatz ein:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb187-1"><a href="5-2-regression.html#cb187-1"></a><span class="kw">egen</span> mean_var2 = <span class="kw">mean</span>(var2)</span>
<span id="cb187-2"><a href="5-2-regression.html#cb187-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2
## 1    1    2      4.75
## 2    2    4      4.75
## 3    7    7      4.75
## 4    8    6      4.75</code></pre>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-38-1.png" width="80%" style="display: block; margin: auto;" />
Müssten wir eine Prognose für die Werte von <code>var2</code> abgeben, wäre das arith. Mittel eine gute Wahl. Die <strong>vorhergesagten Werte</strong> werden jeweils auf der Linie für das arith. Mittel liegen.</p>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-39-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="residuen" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Residuen</h3>
<p>Allerdings liegen wir mit dem arith. Mittel dann immer auch Stück daneben. Diese Abweichung zwischen dem tatsächlichen und dem vorhergesagten Wert wird als <strong>Residuum</strong> bezeichnet, in unserem Beispiel ist das jeweils die Differenz zwischen <code>var2</code> und <code>mean</code>:
<span class="math display">\[Residuum = beobachteter\, Wert \; - \; vorhergesagter\,Wert\]</span>
Als Formel wird das in der Regel wie folgt dargestellt:
<span class="math display">\[\epsilon_{\text{i}} = \text{y}_{i} - \hat{\text{y}}_{i}\]</span></p>
<p>Wir können also die Residuen als Differenz zwischen <code>var2</code> und <code>mean</code> berechnen und in <code>df</code> ablegen:</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb189-1"><a href="5-2-regression.html#cb189-1"></a><span class="kw">gen</span> m_abw = var2 - mean_var2</span>
<span id="cb189-2"><a href="5-2-regression.html#cb189-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw
## 1    1    2      4.75 -2.75
## 2    2    4      4.75 -0.75
## 3    7    7      4.75  2.25
## 4    8    6      4.75  1.25</code></pre>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-42-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p><em>Was bedeutet also ein negativer oder ein positiver Wert für das Residuum?</em></p>
<p>Die horizontale Linie für das arithm. Mittel ist aber sehr deutlich nicht die beste Methode, um die Werte für <code>var2</code> vorherzusagen. In der Graphik können wir deutlich sehen, dass die Werte “weiter links”, also mit geringeren Werten für <code>var1</code>, auch geringere Werte für <code>var2</code> aufweisen. Wir könnten also unseren Vorhersagefehler bzw. das <em>Residuum</em> minimieren indem wir die Linie drehen. Die Idee der Regressionsanalyse ist es dabei, die Residuuen zu minimieren. Was würde aber passieren wenn wir die Residuen aus der Mittelwertsvorhersage aufsummieren, um Sie dann zu minimieren?</p>
</div>
<div id="quadrierte-residuen" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Quadrierte Residuen</h3>
<p>Mit <code>tabstat ..., s(sum)</code> können wir die Summe für eine Variable bilden:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb191-1"><a href="5-2-regression.html#cb191-1"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw
## 1    1    2      4.75 -2.75
## 2    2    4      4.75 -0.75
## 3    7    7      4.75  2.25
## 4    8    6      4.75  1.25</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb193-1"><a href="5-2-regression.html#cb193-1"></a><span class="kw">tabstat</span> m_abw, <span class="fu">s</span>(<span class="kw">sum</span>)</span></code></pre></div>
<pre><code>## 
## 
## . use &quot;regression_bsp.dta&quot;, cl. egen mean_var2 = mean(var2)
## 
## . gen m_abw = var2 - mean_var2
## 
## . tabstat m_abw, s(sum)
## 
##     variable |       sum
## -------------+----------
##        m_abw |         0
## ------------------------</code></pre>
<p><strong>Die Summe der Resiuden auf Basis des arith. Mittels ist immer Null!</strong><br />
Anders formuliert: die gestrichelten Linien nach oben sind in Summe genauso lang wie gestrichelten Linien nach unten.
Die Lösung ist die Residuen zu quadrieren. So ergibt sich eine Kennzahl, die wir minimieren können:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb195-1"><a href="5-2-regression.html#cb195-1"></a><span class="kw">gen</span> m_abw2 = m_abw^2 </span>
<span id="cb195-2"><a href="5-2-regression.html#cb195-2"></a><span class="kw">tabstat</span> m_abw2, <span class="fu">s</span>(<span class="kw">sum</span>)</span></code></pre></div>
<pre><code>## 
## 
## . use &quot;regression_bsp.dta&quot;, cl. egen mean_var2 = mean(var2)
## 
## . gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . predict pred_vorher, xb
## 
## . gen res = var2 - pred_vorher 
## 
## . gen res2 = res^2
## 
## . set linesize 90
## 
## . reg var2 var1
## 
##       Source |       SS       df       MS              Number of obs =       4
## -------------+------------------------------           F(  1,     2) =   11.07
##        Model |  12.4932432     1  12.4932432           Prob &gt; F      =  0.0797
##     Residual |  2.25675676     2  1.12837838           R-squared     =  0.8470
## -------------+------------------------------           Adj R-squared =  0.7705
##        Total |       14.75     3  4.91666667           Root MSE      =  1.0623
## 
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------
## 
## . gen m_abw2 = m_abw^2 
## 
## . tabstat m_abw2, s(sum)
## 
##     variable |       sum
## -------------+----------
##       m_abw2 |     14.75
## ------------------------</code></pre>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2
## 1    1    2      4.75 -2.75 7.5625
## 2    2    4      4.75 -0.75 0.5625
## 3    7    7      4.75  2.25 5.0625
## 4    8    6      4.75  1.25 1.5625</code></pre>
</div>
<div id="interpretation-der-regression" class="section level3">
<h3><span class="header-section-number">5.2.5</span> Interpretation der Regression</h3>
<p>Die Minimierung erledigt <code>reg</code> für uns. Hier geben wir zuerst das Merkmal an, das auf der y-Achse liegt (die <em>abhängige</em> Variable) und dann das Merkmal für die x-Achse (<em>unabhängige</em> Variable) an. Ein positiver Wert unter <code>var1</code> bedeutet, dass unsere Gerade von links nach rechts ansteigt und ein negativer eine fallende Linie bedeuten würde. Der Wert unter <code>var1</code> gibt an, um <em>wieviel sich die Gerade pro “Schritt nach rechts” nach oben/unten verändert</em>. Die Gerade steigt also pro Einheit von <code>var1</code> um 0.5810811:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb198-1"><a href="5-2-regression.html#cb198-1"></a><span class="kw">reg</span> var2 var1</span></code></pre></div>
<pre><code>## 
## 
## . use &quot;regression_bsp.dta&quot;, cl. qui egen mean_var2 = mean(var2)
## 
## . qui gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . qui predict pred_vorher, xb
## 
## . qui gen res = var2 - pred_vorher 
## 
## . qui gen res2 = res^2
## 
## . qui set linesize 90
## 
## . reg var2 var1
## 
##       Source |       SS       df       MS              Number of obs =       4
## -------------+------------------------------           F(  1,     2) =   11.07
##        Model |  12.4932432     1  12.4932432           Prob &gt; F      =  0.0797
##     Residual |  2.25675676     2  1.12837838           R-squared     =  0.8470
## -------------+------------------------------           Adj R-squared =  0.7705
##        Total |       14.75     3  4.91666667           Root MSE      =  1.0623
## 
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------</code></pre>
<p>In unserer Grafik sieht diese Gerade so aus:
<img src="Stata_Skript_files/figure-html/unnamed-chunk-53-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="vorhergesagte-werte" class="section level3">
<h3><span class="header-section-number">5.2.6</span> Vorhergesagte Werte</h3>
<p>Wie hoch ist nun der vorhergesagte Wert auf Basis der blauen Gerade?
Die vohergesagten Werte aus <code>reg var2 var1</code> entsprechen einfach der Summe aus dem Wert unter <code>Intercept</code> und dem Koeffizienten neben <code>var1</code> multipliziert mit dem jeweiligen Wert für <code>var1</code>.<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></p>
<div class="sourceCode" id="cb200"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb200-1"><a href="5-2-regression.html#cb200-1"></a><span class="kw">reg</span> var2 var1, <span class="kw">noheader</span></span></code></pre></div>
<pre><code>## 
## 
## . use &quot;regression_bsp.dta&quot;, cl. qui egen mean_var2 = mean(var2)
## 
## . qui gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . qui predict pred_vorher, xb
## 
## . qui gen res = var2 - pred_vorher 
## 
## . qui gen res2 = res^2
## 
## . qui set linesize 90
## 
## . reg var2 var1, noheader
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------</code></pre>
<p>Vorhergesagte Werte werden mit <span class="math inline">\(\widehat{var2}\)</span> bezeichnet - der ^ steht dabei für “vorhergesagt”:</p>
<p><span class="math display">\[\widehat{var2}=\texttt{Intercept} + 0.5811 \times \texttt{var1}\]</span><br />
Für die erste Zeile ergibt sich also folgender vorhergesagter Wert: 2.1351+0.5811*1= 2.7162</p>
<p>Also könnten wir mit <code>gen</code> die vorhergesagten Werte “manuell” berechnen:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb202-1"><a href="5-2-regression.html#cb202-1"></a><span class="kw">gen</span> man_vorhers = 2.1351 + 0.5811 * var1</span></code></pre></div>
<p>Die vorhergesagten Werte können wir auch mit <code>predict</code> berechnen und in einer neuen Variable <code>pred_vorher</code> ablegen:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb203-1"><a href="5-2-regression.html#cb203-1"></a><span class="kw">predict</span> pred1, <span class="kw">xb</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2 man_vorhers pred_vorher
## 1    1    2      4.75 -2.75 7.5625      2.7162    2.716216
## 2    2    4      4.75 -0.75 0.5625      3.2973    3.297297
## 3    7    7      4.75  2.25 5.0625      6.2028    6.202703
## 4    8    6      4.75  1.25 1.5625      6.7839    6.783784</code></pre>
<p>Die Grafik zeigt wie Vorhersagen auf Basis des Regressionsmodells aussehen: Sie entsprechen den Werten auf der blauen Geraden (der sog. Regressionsgeraden) an den jeweiligen Stellen für <code>var1</code>.
<img src="Stata_Skript_files/figure-html/unnamed-chunk-59-1.png" width="80%" style="display: block; margin: auto;" />
Wir können erkennen, dass die hellblauen Punkte (also die Vorhersagen des Regressionsmodells) deutlich näher an den tatsächlichen Punkten liegen als die orangen Vorhersagen auf Basis des <code>mean</code>.</p>
</div>
<div id="residuen-teil-2" class="section level3">
<h3><span class="header-section-number">5.2.7</span> Residuen Teil 2</h3>
<p>Trotzdem sind auch die hellblauen Punkte nicht deckungsgleich mit den tatsächlichen Werten. Es gibt also auch hier wieder Residuen, also Abweichungen des beobachteten vom vorhergesagten Wert. Wir können diese per Hand berechnen als Differenz zwischen dem tatsächlichen und dem vorhergesagten Wert:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb205-1"><a href="5-2-regression.html#cb205-1"></a><span class="kw">gen</span> res = var2 - pred_vorher </span></code></pre></div>
<p>Oder wir können Sie mit <code>predict neue_variable , residuals</code> erstellen:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb206-1"><a href="5-2-regression.html#cb206-1"></a><span class="kw">reg</span> var2 var1 <span class="co">// zunächst nochmal die regression laufen lassen</span></span>
<span id="cb206-2"><a href="5-2-regression.html#cb206-2"></a><span class="kw">predict</span> p_res , residuals</span>
<span id="cb206-3"><a href="5-2-regression.html#cb206-3"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2 man_vorhers pred_vorher        res      p_res
## 1    1    2      4.75 -2.75 7.5625      2.7162    2.716216 -0.7162162 -0.7162162
## 2    2    4      4.75 -0.75 0.5625      3.2973    3.297297  0.7027027  0.7027027
## 3    7    7      4.75  2.25 5.0625      6.2028    6.202703  0.7972973  0.7972973
## 4    8    6      4.75  1.25 1.5625      6.7839    6.783784 -0.7837838 -0.7837838</code></pre>
<p>Hier sind die Residuen für <code>p_res</code> als hellblaue Linien eingezeichnet:
<img src="Stata_Skript_files/figure-html/unnamed-chunk-63-1.png" width="80%" style="display: block; margin: auto;" />
<em>Wie groß ist die Summe der Residuen für <code>lm</code>?</em></p>
</div>
<div id="modellgüte" class="section level3">
<h3><span class="header-section-number">5.2.8</span> Modellgüte</h3>
<p>Um zu beurteilen, um wieviel besser unsere Gerade aus <code>reg</code> die Werte vorhersagt kann als der <code>mean</code> können wir die Summe der quadrierten Residuen vergleichen. Dazu quadrieren wir also die Residuen:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb208-1"><a href="5-2-regression.html#cb208-1"></a><span class="kw">gen</span> res2 = res^2</span>
<span id="cb208-2"><a href="5-2-regression.html#cb208-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2 man_vorhers pred_vorher        res      res2
## 1    1    2      4.75 -2.75 7.5625      2.7162    2.716216 -0.7162162 0.5129657
## 2    2    4      4.75 -0.75 0.5625      3.2973    3.297297  0.7027027 0.4937911
## 3    7    7      4.75  2.25 5.0625      6.2028    6.202703  0.7972973 0.6356830
## 4    8    6      4.75  1.25 1.5625      6.7839    6.783784 -0.7837838 0.6143170</code></pre>
<p>Dann können wir die Summen der quadierten Abweichungen aus der Mittelwertregel und dem Regressionsmodell vergleichen:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb210-1"><a href="5-2-regression.html#cb210-1"></a>dis 7.5625+0.5625+5.0625+1.5625 <span class="co">// abw2 aus Mittelwertsregel</span></span>
<span id="cb210-2"><a href="5-2-regression.html#cb210-2"></a>## </span>
<span id="cb210-3"><a href="5-2-regression.html#cb210-3"></a>## </span>
<span id="cb210-4"><a href="5-2-regression.html#cb210-4"></a>## . dis 7.5625+0.5625+5.0625+1.5625 <span class="co">// abw2 aus Mit&gt; wertsregel</span></span>
<span id="cb210-5"><a href="5-2-regression.html#cb210-5"></a>## 14.75</span></code></pre></div>
<div class="sourceCode" id="cb211"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb211-1"><a href="5-2-regression.html#cb211-1"></a>dis 0.5129657+0.4937911+0.6356830+0.6143170 <span class="co">// res2 aus regressionsmodell</span></span>
<span id="cb211-2"><a href="5-2-regression.html#cb211-2"></a>## </span>
<span id="cb211-3"><a href="5-2-regression.html#cb211-3"></a>## </span>
<span id="cb211-4"><a href="5-2-regression.html#cb211-4"></a>## . dis 0.5129657+0.4937911+0.6356830+0.6143170 <span class="co">// &gt; 2 aus regressionsmodell</span></span>
<span id="cb211-5"><a href="5-2-regression.html#cb211-5"></a>## 2.2567568</span></code></pre></div>
<p>Zum Beispiel können wir uns fragen, um wieviel sich die Summe der quadrierten Residuen verringert wenn wir statt des <code>mean</code> unser <code>reg</code>-Modell verwenden:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb212-1"><a href="5-2-regression.html#cb212-1"></a>dis 14.75 -  2.256757</span>
<span id="cb212-2"><a href="5-2-regression.html#cb212-2"></a>## </span>
<span id="cb212-3"><a href="5-2-regression.html#cb212-3"></a>## </span>
<span id="cb212-4"><a href="5-2-regression.html#cb212-4"></a>## . dis 14.75 -  2.25612.493243</span></code></pre></div>
<p>Wenn wir diese Veränderung ins Verhältnis mit dem “Ausgangswert”, also den Residuen aus der Mittelwertregel setzen, dann erhalten wir das <span class="math inline">\(R^{2}\)</span> für unser <code>reg</code>-Modell. Dieses gibt die prozentuale Verringerung der Residuen durch das <code>reg</code>-Modell im Vergleich zur Mittelwertregel an:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb213-1"><a href="5-2-regression.html#cb213-1"></a>dis (14.75 -  2.256757) / 14.75</span>
<span id="cb213-2"><a href="5-2-regression.html#cb213-2"></a>## </span>
<span id="cb213-3"><a href="5-2-regression.html#cb213-3"></a>## </span>
<span id="cb213-4"><a href="5-2-regression.html#cb213-4"></a>## . dis (14.75 -  2.256757) / 14.84699953</span></code></pre></div>
<p>Unser Regressionsmodell kann also 84,7% der Streuung um den Mittelwert erklären. Dieser Wert wird auch als <span class="math inline">\(R^2\)</span> bezeichnet. Im Regressionsoutput können wir das <span class="math inline">\(R^2\)</span> oben rechts unter <code>R-squared</code> ablesen.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb214-1"><a href="5-2-regression.html#cb214-1"></a><span class="kw">reg</span> var2 var1</span>
<span id="cb214-2"><a href="5-2-regression.html#cb214-2"></a>## </span>
<span id="cb214-3"><a href="5-2-regression.html#cb214-3"></a>## </span>
<span id="cb214-4"><a href="5-2-regression.html#cb214-4"></a>## . <span class="kw">reg</span> var2 vno variables defined</span>
<span id="cb214-5"><a href="5-2-regression.html#cb214-5"></a>## <span class="fu">r</span>(111);</span>
<span id="cb214-6"><a href="5-2-regression.html#cb214-6"></a>## </span>
<span id="cb214-7"><a href="5-2-regression.html#cb214-7"></a>## <span class="kw">end</span> <span class="kw">of</span> <span class="kw">do</span>-file</span>
<span id="cb214-8"><a href="5-2-regression.html#cb214-8"></a>## <span class="fu">r</span>(111);</span></code></pre></div>
<p>Außerdem sehen wir oben links in der Spalte <code>SS</code> die “Sum of Squares”. Hier finden wir auch die Werte von oben wieder: unter Total ist die Summe der quadrierten Abweichungen der beobachteten Werte vom arith. Mittel angegeben (<code>14.75</code>, sozusagen die Summe der <code>m_abw2</code> von oben). Residual gibt die Summe der Abweichungsquadrate zwischen den beobachteten Werten und den vorhergesagten Werten der Regression (<code>2.256..</code>, Die Summe von <code>res2</code>).</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="8">
<li id="fn8"><p>Mehr zu <code>egen</code> in Kapitel <a href="11-8-egen.html#egen">11.8</a><a href="5-2-regression.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>Die Option <code>noheader</code> macht den Output von <code>reg</code> etwas übersichtlicher.<a href="5-2-regression.html#fnref9" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<p style="text-align: center;">
<a href="5-1-metrisch-skalierte-variablen.html"><button class="btn btn-default">Previous</button></a>
<a href="5-3-ordinal-skalierte-merkmale.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
