<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="5.7 Anhang | GESIS Methodenseminar 2020" />
<meta property="og:type" content="book" />


<meta property="og:description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020" />


<meta name="author" content="Andreas Filser" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020">

<title>5.7 Anhang | GESIS Methodenseminar 2020</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#herzlich-willkommen">Herzlich Willkommen!</a></li>
<li class="has-sub"><a href="1-Stata1.html#Stata1"><span class="toc-section-number">1</span> Einstieg in Stata</a><ul>
<li><a href="1-1-taschenrechner.html#taschenrechner"><span class="toc-section-number">1.1</span> Taschenrechner</a></li>
<li><a href="1-2-darstellung-in-diesem-skript.html#darstellung-in-diesem-skript"><span class="toc-section-number">1.2</span> Darstellung in diesem Skript</a></li>
<li><a href="1-3-dofile-editor.html#dofile-editor"><span class="toc-section-number">1.3</span> DoFile Editor</a></li>
<li><a href="1-4-datensätze-laden.html#datensätze-laden"><span class="toc-section-number">1.4</span> Datensätze laden</a></li>
<li><a href="1-5-daten-codebücher-fragebogen.html#daten-codebücher-fragebogen"><span class="toc-section-number">1.5</span> Daten, Codebücher, Fragebogen</a></li>
<li class="has-sub"><a href="1-6-überblicksbefehle.html#überblicksbefehle"><span class="toc-section-number">1.6</span> Überblicksbefehle</a><ul>
<li><a href="1-6-überblicksbefehle.html#describe"><span class="toc-section-number">1.6.1</span> <code>describe</code></a></li>
<li><a href="1-6-überblicksbefehle.html#browse"><span class="toc-section-number">1.6.2</span> <code>browse</code></a></li>
<li><a href="1-6-überblicksbefehle.html#list"><span class="toc-section-number">1.6.3</span> <code>list</code></a></li>
<li><a href="1-6-überblicksbefehle.html#lookfor"><span class="toc-section-number">1.6.4</span> <code>lookfor</code></a></li>
</ul></li>
<li><a href="1-7-löschen.html#löschen"><span class="toc-section-number">1.7</span> löschen</a></li>
<li><a href="1-8-if-bedingung-nur-manche-zeilen-ansehen.html#if-bedingung---nur-manche-zeilen-ansehen"><span class="toc-section-number">1.8</span> if Bedingung - nur manche Zeilen ansehen</a></li>
<li><a href="1-9-U1.html#U1"><span class="toc-section-number">1.9</span> Übungen 1</a></li>
<li><a href="1-10-profi-übungen-1.html#profi-übungen-1"><span class="toc-section-number">1.10</span> Profi-Übungen 1</a></li>
<li class="has-sub"><a href="1-11-anhang-1.html#anhang-1"><span class="toc-section-number">1.11</span> Anhang 1</a><ul>
<li><a href="1-11-anhang-1.html#var_types"><span class="toc-section-number">1.11.1</span> Variablentypen</a></li>
<li><a href="1-11-anhang-1.html#otherfmts"><span class="toc-section-number">1.11.2</span> import anderer Dateiformate</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="2-Stata2.html#Stata2"><span class="toc-section-number">2</span> Arbeiten mit Datensätzen in Stata</a><ul>
<li><a href="2-1-vorab-befehlsstruktur-hilfe.html#vorab-befehlsstruktur-hilfe"><span class="toc-section-number">2.1</span> Vorab: Befehlsstruktur &amp; Hilfe</a></li>
<li><a href="2-2-auszählen-überblick-erhalten.html#auszählen-überblick-erhalten"><span class="toc-section-number">2.2</span> Auszählen &amp; Überblick erhalten</a></li>
<li><a href="2-3-neue-variablen-erstellen.html#neue-variablen-erstellen"><span class="toc-section-number">2.3</span> Neue Variablen erstellen</a></li>
<li><a href="2-4-bestehende-variablen-verändern.html#bestehende-variablen-verändern"><span class="toc-section-number">2.4</span> Bestehende Variablen verändern</a></li>
<li><a href="2-5-gen-ist-gut-kontrolle-ist-besser.html#gen-ist-gut-kontrolle-ist-besser"><span class="toc-section-number">2.5</span> gen ist gut, Kontrolle ist besser</a></li>
<li><a href="2-6-fehlende-werte.html#fehlende-werte"><span class="toc-section-number">2.6</span> Fehlende Werte</a></li>
<li><a href="2-7-if-bedingungen-und-fehlende-werte.html#if-bedingungen-und-fehlende-werte"><span class="toc-section-number">2.7</span> if Bedingungen und fehlende Werte</a></li>
<li><a href="2-8-keep-drop.html#keep-drop"><span class="toc-section-number">2.8</span> keep &amp; drop</a></li>
<li><a href="2-9-labels-und-if-bedingungen.html#labels-und-if-bedingungen"><span class="toc-section-number">2.9</span> Labels und if-Bedingungen</a></li>
<li><a href="2-10-nochmal-von-vorne-daten-neu-laden.html#nochmal-von-vorne-daten-neu-laden"><span class="toc-section-number">2.10</span> Nochmal von vorne: Daten neu laden</a></li>
<li><a href="2-11-speichern.html#speichern"><span class="toc-section-number">2.11</span> Speichern</a></li>
<li><a href="2-12-übungen-2.html#übungen-2"><span class="toc-section-number">2.12</span> Übungen 2</a></li>
<li><a href="2-13-profi-übungen-2.html#profi-übungen-2"><span class="toc-section-number">2.13</span> Profi-Übungen 2</a></li>
</ul></li>
<li class="has-sub"><a href="3-desc1.html#desc1"><span class="toc-section-number">3</span> Deskriptive Statistik</a><ul>
<li class="has-sub"><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#kategoriale-merkmale-mit-tabulate-beschreiben"><span class="toc-section-number">3.1</span> Kategoriale Merkmale mit <code>tabulate</code> beschreiben</a><ul>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#zwei-variablen-eine-tabelle-kontingenztabellen"><span class="toc-section-number">3.1.1</span> Zwei Variablen, eine Tabelle: Kontingenztabellen</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#in-prozent-relative-häufigkeiten"><span class="toc-section-number">3.1.2</span> In Prozent: Relative Häufigkeiten</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-1-zeilenprozente"><span class="toc-section-number">3.1.3</span> pro Gruppe 1: Zeilenprozente</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-2-spaltenprozente"><span class="toc-section-number">3.1.4</span> pro Gruppe 2: Spaltenprozente</a></li>
</ul></li>
<li class="has-sub"><a href="3-2-metrische-variablen-beschreiben.html#metrische-variablen-beschreiben"><span class="toc-section-number">3.2</span> Metrische Variablen beschreiben</a><ul>
<li><a href="3-2-metrische-variablen-beschreiben.html#summarize"><span class="toc-section-number">3.2.1</span> <code>summarize</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#tabstat"><span class="toc-section-number">3.2.2</span> <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#by_vgl"><span class="toc-section-number">3.2.3</span> Kennzahlen vergleichen mit <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#streu"><span class="toc-section-number">3.2.4</span> Streuungsmaße: Varianz, Standardabweichung, Variationskoeffizient</a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#gini-koeffizient"><span class="toc-section-number">3.2.5</span> Gini-Koeffizient</a></li>
</ul></li>
<li class="has-sub"><a href="3-3-übungen-3.html#übungen-3"><span class="toc-section-number">3.3</span> Übungen 3</a><ul>
<li><a href="3-3-übungen-3.html#tab"><span class="toc-section-number">3.3.1</span> Übung 3-1</a></li>
<li><a href="3-3-übungen-3.html#met"><span class="toc-section-number">3.3.2</span> Übung 3-2</a></li>
<li><a href="3-3-übungen-3.html#weitere-übungen-3"><span class="toc-section-number">3.3.3</span> Weitere Übungen 3</a></li>
</ul></li>
<li><a href="3-4-profi-übungen-3.html#profi-übungen-3"><span class="toc-section-number">3.4</span> Profi-Übungen 3</a></li>
<li class="has-sub"><a href="3-5-anhang-kap-3.html#anhang-kap-3"><span class="toc-section-number">3.5</span> Anhang Kap 3</a><ul>
<li><a href="3-5-anhang-kap-3.html#vlabel"><span class="toc-section-number">3.5.1</span> labels vergeben</a></li>
<li><a href="3-5-anhang-kap-3.html#variance"><span class="toc-section-number">3.5.2</span> Varianz erklärt</a></li>
<li><a href="3-5-anhang-kap-3.html#sk_kur"><span class="toc-section-number">3.5.3</span> Schiefe &amp; Wölbung</a></li>
<li><a href="3-5-anhang-kap-3.html#bys_su"><span class="toc-section-number">3.5.4</span> Kombination von <code>summarize</code> mit dem <code>by</code>-Präfix</a></li>
<li><a href="3-5-anhang-kap-3.html#if_vgl"><span class="toc-section-number">3.5.5</span> Kennzahlvergleiche mit <code>if</code></a></li>
<li><a href="3-5-anhang-kap-3.html#kennzahlvergleich-mit-tabulate-und-der-option-summarize"><span class="toc-section-number">3.5.6</span> Kennzahlvergleich mit <code>tabulate</code> und der Option <code>summarize()</code></a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="4-dataviz.html#dataviz"><span class="toc-section-number">4</span> Datenvisualisierung in Stata</a><ul>
<li class="has-sub"><a href="4-1-visualisierung-einer-variable.html#visualisierung-einer-variable"><span class="toc-section-number">4.1</span> Visualisierung einer Variable</a><ul>
<li><a href="4-1-visualisierung-einer-variable.html#metrische-variablen"><span class="toc-section-number">4.1.1</span> metrische Variablen</a></li>
<li><a href="4-1-visualisierung-einer-variable.html#bar_col"><span class="toc-section-number">4.1.2</span> Kategoriale Variablen</a></li>
</ul></li>
<li><a href="4-2-verteilungen-vergleichen-mit-facetten.html#verteilungen-vergleichen-mit-facetten"><span class="toc-section-number">4.2</span> Verteilungen vergleichen mit Facetten</a></li>
<li class="has-sub"><a href="4-3-bivar-plot.html#bivar_plot"><span class="toc-section-number">4.3</span> Gemeinsame Verteilung zweier Variablen</a><ul>
<li><a href="4-3-bivar-plot.html#mosaikplot"><span class="toc-section-number">4.3.1</span> Mosaikplot</a></li>
<li><a href="4-3-bivar-plot.html#streudiagramm"><span class="toc-section-number">4.3.2</span> Streudiagramm</a></li>
</ul></li>
<li><a href="4-4-weitere-twoway-grafiken.html#weitere-twoway-grafiken"><span class="toc-section-number">4.4</span> Weitere <code>twoway</code> Grafiken</a></li>
<li><a href="4-5-twoway-comb.html#twoway_comb"><span class="toc-section-number">4.5</span> Kombinieren von zwei twoway-Grafiken</a></li>
<li><a href="4-6-gruppierte-boxplots.html#gruppierte-boxplots"><span class="toc-section-number">4.6</span> Gruppierte Boxplots</a></li>
<li class="has-sub"><a href="4-7-übungen-4.html#übungen-4"><span class="toc-section-number">4.7</span> Übungen 4</a><ul>
<li><a href="4-7-übungen-4.html#plt1"><span class="toc-section-number">4.7.1</span> Übung 4-1</a></li>
<li><a href="4-7-übungen-4.html#plt2"><span class="toc-section-number">4.7.2</span> Übung 4-2</a></li>
<li><a href="4-7-übungen-4.html#weitere-übungen-kap4"><span class="toc-section-number">4.7.3</span> Weitere Übungen Kap4</a></li>
</ul></li>
<li class="has-sub"><a href="4-8-optionen.html#optionen"><span class="toc-section-number">4.8</span> Optionen</a><ul>
<li><a href="4-8-optionen.html#title"><span class="toc-section-number">4.8.1</span> Titel</a></li>
<li><a href="4-8-optionen.html#achsenbeschriftung"><span class="toc-section-number">4.8.2</span> Achsenbeschriftung</a></li>
<li><a href="4-8-optionen.html#text-einfügen"><span class="toc-section-number">4.8.3</span> Text einfügen</a></li>
<li><a href="4-8-optionen.html#font"><span class="toc-section-number">4.8.4</span> Schriftart &amp; Textgröße</a></li>
<li><a href="4-8-optionen.html#legend"><span class="toc-section-number">4.8.5</span> Legende</a></li>
<li><a href="4-8-optionen.html#mark"><span class="toc-section-number">4.8.6</span> Marker</a></li>
<li><a href="4-8-optionen.html#color"><span class="toc-section-number">4.8.7</span> Farben</a></li>
<li><a href="4-8-optionen.html#vorlagen"><span class="toc-section-number">4.8.8</span> Vorlagen</a></li>
</ul></li>
<li class="has-sub"><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#anhang-beispiele-zum-selbst-anpassen"><span class="toc-section-number">4.9</span> Anhang &amp; Beispiele zum selbst anpassen</a><ul>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#boxplot"><span class="toc-section-number">4.9.1</span> Boxplot</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#scatterplot"><span class="toc-section-number">4.9.2</span> Scatterplot</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#pyramid"><span class="toc-section-number">4.9.3</span> Bevölkerungspyramide</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#boxplot1"><span class="toc-section-number">4.9.4</span> Boxplot</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="5-zshg.html#zshg"><span class="toc-section-number">5</span> Zusammenhangsmaße</a><ul>
<li class="has-sub"><a href="5-1-zshg-met.html#zshg_met"><span class="toc-section-number">5.1</span> Metrisch skalierte Variablen</a><ul>
<li><a href="5-1-zshg-met.html#cor"><span class="toc-section-number">5.1.1</span> Korrelationskoeffizient</a></li>
<li><a href="5-1-zshg-met.html#regression"><span class="toc-section-number">5.1.2</span> Regression</a></li>
<li><a href="5-1-zshg-met.html#vorhergesagte-werte"><span class="toc-section-number">5.1.3</span> vorhergesagte Werte</a></li>
</ul></li>
<li class="has-sub"><a href="5-2-zshg-ord.html#zshg_ord"><span class="toc-section-number">5.2</span> Ordinal skalierte Merkmale</a><ul>
<li><a href="5-2-zshg-ord.html#spear"><span class="toc-section-number">5.2.1</span> Spearman- Rangkorrelation</a></li>
<li><a href="5-2-zshg-ord.html#tau"><span class="toc-section-number">5.2.2</span> Konkordanzmaße</a></li>
</ul></li>
<li class="has-sub"><a href="5-3-zshg-nom.html#zshg_nom"><span class="toc-section-number">5.3</span> Nominal skalierte Variablen</a><ul>
<li><a href="5-3-zshg-nom.html#OR"><span class="toc-section-number">5.3.1</span> Odds Ratio</a></li>
<li><a href="5-3-zshg-nom.html#chi2"><span class="toc-section-number">5.3.2</span> Chi²-basierte Maße</a></li>
<li><a href="5-3-zshg-nom.html#cramers-upsilon"><span class="toc-section-number">5.3.3</span> Cramer’s <span class="math inline">\(\upsilon\)</span></a></li>
<li><a href="5-3-zshg-nom.html#phi"><span class="toc-section-number">5.3.4</span> <span class="math inline">\(\phi\)</span></a></li>
</ul></li>
<li><a href="5-4-welches-maß-richtig.html#welches-maß-richtig"><span class="toc-section-number">5.4</span> Welches Maß richtig?</a></li>
<li class="has-sub"><a href="5-5-übungen-5.html#übungen-5"><span class="toc-section-number">5.5</span> Übungen 5</a><ul>
<li><a href="5-5-übungen-5.html#auf_met"><span class="toc-section-number">5.5.1</span> Übung 5-1</a></li>
<li><a href="5-5-übungen-5.html#auf_ord"><span class="toc-section-number">5.5.2</span> Übung 5-2</a></li>
<li><a href="5-5-übungen-5.html#auf_nom"><span class="toc-section-number">5.5.3</span> Übung 5-3</a></li>
<li><a href="5-5-übungen-5.html#weitere-übungen-5"><span class="toc-section-number">5.5.4</span> Weitere Übungen 5</a></li>
</ul></li>
<li><a href="5-6-profi-übungen-5.html#profi-übungen-5"><span class="toc-section-number">5.6</span> Profi-Übungen 5</a></li>
<li class="has-sub"><a href="5-7-anhang.html#anhang"><span class="toc-section-number">5.7</span> Anhang</a><ul>
<li><a href="5-7-anhang.html#reg"><span class="toc-section-number">5.7.1</span> Idee einer Regression</a></li>
<li><a href="5-7-anhang.html#resid"><span class="toc-section-number">5.7.2</span> Residuen</a></li>
<li><a href="5-7-anhang.html#quad_res"><span class="toc-section-number">5.7.3</span> Quadrierte Residuen</a></li>
<li><a href="5-7-anhang.html#interpretation-der-regression"><span class="toc-section-number">5.7.4</span> Interpretation der Regression</a></li>
<li><a href="5-7-anhang.html#reg_pred"><span class="toc-section-number">5.7.5</span> Vorhergesagte Werte</a></li>
<li><a href="5-7-anhang.html#resid2"><span class="toc-section-number">5.7.6</span> Residuen Teil 2</a></li>
<li><a href="5-7-anhang.html#r2"><span class="toc-section-number">5.7.7</span> Modellgüte</a></li>
<li><a href="5-7-anhang.html#indiff"><span class="toc-section-number">5.7.8</span> Indifferenztabelle</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="6-zshg2.html#zshg2"><span class="toc-section-number">6</span> Zusammenhänge 2</a><ul>
<li><a href="6-1-zusammenhänge-vergleichen.html#zusammenhänge-vergleichen"><span class="toc-section-number">6.1</span> Zusammenhänge vergleichen</a></li>
<li><a href="6-2-zusammenhänge-visualisieren.html#zusammenhänge-visualisieren"><span class="toc-section-number">6.2</span> Zusammenhänge visualisieren</a></li>
<li class="has-sub"><a href="6-3-kategoriale-zusammenhänge.html#kategoriale-zusammenhänge"><span class="toc-section-number">6.3</span> Kategoriale Zusammenhänge</a><ul>
<li><a href="6-3-kategoriale-zusammenhänge.html#ordinale-zusammenhangsmaße-vergleichen"><span class="toc-section-number">6.3.1</span> Ordinale Zusammenhangsmaße vergleichen</a></li>
<li><a href="6-3-kategoriale-zusammenhänge.html#vergleich-visualisieren"><span class="toc-section-number">6.3.2</span> Vergleich visualisieren</a></li>
<li><a href="6-3-kategoriale-zusammenhänge.html#nominale-zusammenhangsmaße-vergleichen"><span class="toc-section-number">6.3.3</span> Nominale Zusammenhangsmaße vergleichen</a></li>
</ul></li>
<li class="has-sub"><a href="6-4-übungen-6.html#übungen-6"><span class="toc-section-number">6.4</span> Übungen 6</a><ul>
<li><a href="6-4-übungen-6.html#met_vgl"><span class="toc-section-number">6.4.1</span> Übung 6-1</a></li>
<li><a href="6-4-übungen-6.html#ord_vgl"><span class="toc-section-number">6.4.2</span> Übung 6-2</a></li>
<li><a href="6-4-übungen-6.html#nom_vgl"><span class="toc-section-number">6.4.3</span> Übung 6-3</a></li>
<li><a href="6-4-übungen-6.html#weitere-übungen-kap-6"><span class="toc-section-number">6.4.4</span> Weitere Übungen Kap 6</a></li>
</ul></li>
<li class="has-sub"><a href="5-7-anhang.html#anhang"><span class="toc-section-number">6.5</span> Anhang</a><ul>
<li><a href="6-5-anhang.html#lpattern"><span class="toc-section-number">6.5.1</span> Optionen für <code>lpattern</code></a></li>
<li><a href="6-5-anhang.html#scatterplot-für-kategoriale-merkmale"><span class="toc-section-number">6.5.2</span> Scatterplot für kategoriale Merkmale</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="7-inf1.html#inf1"><span class="toc-section-number">7</span> Inferenzstatistik I</a><ul>
<li><a href="7-1-inferenz.html#inferenz"><span class="toc-section-number">7.1</span> Inferenz</a></li>
<li class="has-sub"><a href="7-2-parametrische-ki-schätzung.html#parametrische-ki-schätzung"><span class="toc-section-number">7.2</span> Parametrische KI-Schätzung</a><ul>
<li><a href="7-2-parametrische-ki-schätzung.html#t-z-wert"><span class="toc-section-number">7.2.1</span> t-/z-Wert</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#standardfehler"><span class="toc-section-number">7.2.2</span> Standardfehler</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#kis-berechnen"><span class="toc-section-number">7.2.3</span> KIs berechnen</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#mean"><span class="toc-section-number">7.2.4</span> <code>mean</code></a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#vergleich"><span class="toc-section-number">7.2.5</span> Vergleich</a></li>
</ul></li>
<li><a href="7-3-bootstrapping.html#bootstrapping"><span class="toc-section-number">7.3</span> Bootstrapping</a></li>
<li><a href="7-4-übungen-7.html#übungen-7"><span class="toc-section-number">7.4</span> Übungen 7</a></li>
<li class="has-sub"><a href="7-5-anhang-kap7.html#anhang-kap7"><span class="toc-section-number">7.5</span> Anhang Kap7</a><ul>
<li><a href="7-5-anhang-kap7.html#normalverteilung"><span class="toc-section-number">7.5.1</span> Normalverteilung</a></li>
<li><a href="7-5-anhang-kap7.html#student-t-verteilung"><span class="toc-section-number">7.5.2</span> Student t-Verteilung</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="8-inf2.html#inf2"><span class="toc-section-number">8</span> t-Tests</a><ul>
<li><a href="8-1-hypothesentests.html#hypothesentests"><span class="toc-section-number">8.1</span> Hypothesentests</a></li>
<li class="has-sub"><a href="8-2-t-test.html#t-test"><span class="toc-section-number">8.2</span> t-Test</a><ul>
<li><a href="8-2-t-test.html#beiseitiger-t-test"><span class="toc-section-number">8.2.1</span> beiseitiger t-Test</a></li>
<li><a href="8-2-t-test.html#linksseitiger-t-test"><span class="toc-section-number">8.2.2</span> linksseitiger t-Test</a></li>
<li><a href="8-2-t-test.html#rechtsseitiger-t-test"><span class="toc-section-number">8.2.3</span> rechtsseitiger t-Test</a></li>
</ul></li>
<li><a href="8-3-übungen-8.html#übungen-8"><span class="toc-section-number">8.3</span> Übungen 8</a></li>
<li><a href="8-4-profi-übungen-8.html#profi-übungen-8"><span class="toc-section-number">8.4</span> Profi-Übungen 8</a></li>
<li class="has-sub"><a href="8-5-hinweise.html#hinweise"><span class="toc-section-number">8.5</span> Hinweise</a><ul>
<li><a href="8-5-hinweise.html#auswahl-der-in-vollzeit-beschäftigten-befragten"><span class="toc-section-number">8.5.1</span> Auswahl der in Vollzeit beschäftigten Befragten</a></li>
</ul></li>
</ul></li>
<li><a href="9-hypo.html#hypo"><span class="toc-section-number">9</span> Hypothesentests</a></li>
<li><a href="10-export1.html#export1"><span class="toc-section-number">10</span> Ergebnisexport &amp; weitere Tipps</a></li>
<li class="has-sub"><a href="11-adva.html#adva"><span class="toc-section-number">11</span> Fortgeschrittene Themen</a><ul>
<li><a href="11-1-wertelabels.html#wertelabels"><span class="toc-section-number">11.1</span> Wertelabels</a></li>
<li><a href="11-2-sortieren.html#sortieren"><span class="toc-section-number">11.2</span> sortieren</a></li>
<li><a href="11-3-informationen-aus-mehreren-variablen.html#informationen-aus-mehreren-variablen"><span class="toc-section-number">11.3</span> Informationen aus mehreren Variablen</a></li>
<li><a href="11-4-egen.html#egen"><span class="toc-section-number">11.4</span> egen</a></li>
<li><a href="11-5-gruppierte-berechnungen.html#gruppierte-berechnungen"><span class="toc-section-number">11.5</span> gruppierte Berechnungen</a></li>
<li><a href="11-6-sep1.html#sep1"><span class="toc-section-number">11.6</span> Subgruppen-Variablen erstellen mit <code>separate</code></a></li>
<li><a href="11-7-collapse.html#collapse"><span class="toc-section-number">11.7</span> collapse</a></li>
<li><a href="11-8-indikatoren-umdrehen.html#indikatoren-umdrehen"><span class="toc-section-number">11.8</span> Indikatoren umdrehen</a></li>
<li><a href="11-9-informationen-aus-mehreren-datensätzen.html#informationen-aus-mehreren-datensätzen"><span class="toc-section-number">11.9</span> Informationen aus mehreren Datensätzen</a></li>
<li><a href="11-10-arbeiten-mit-textvariablen.html#arbeiten-mit-textvariablen"><span class="toc-section-number">11.10</span> Arbeiten mit Textvariablen</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="anhang" class="section level2">
<h2><span class="header-section-number">5.7</span> Anhang</h2>
<div id="reg" class="section level3">
<h3><span class="header-section-number">5.7.1</span> Idee einer Regression</h3>
<p>Zum Einstieg betrachten wir zunächst einen (fiktiven) Datensatz mit lediglich 4 Fällen und lediglich zwei Variablen: <code>var1</code> und <code>var2</code>:</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb243-1"><a href="5-7-anhang.html#cb243-1"></a><span class="kw">use</span> <span class="st">&quot;https://github.com/filius23/Stata_Skript/raw/master/regression_bsp.dta&quot;</span>, <span class="kw">clear</span></span>
<span id="cb243-2"><a href="5-7-anhang.html#cb243-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2
## 1    1    2
## 2    2    4
## 3    7    7
## 4    8    6</code></pre>
<p><img src="Stata_Skript_files/figure-html/regplot1-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Ziel der Regression ist es, den Zusammenhang zwischen diesen beiden Variablen zu bestimmen. Gibt es einen Trend, in dem Sinn, dass ein höherer Wert von <code>var1</code> mit einem höheren oder niedrigeren Wert von <code>var2</code> einhergeht?</p>
<p>Etwas anders gesagt könnte man auch fragen, welchen Wert für <code>var2</code> wir vorhersagen würden, wenn wir <code>var1</code> kennen. Ein Ausgangspunkt ist das arithmetische Mittel. Dieses können wir mit <code>mean</code> zB für <code>var2</code> berechnen.<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a> Diesen Wert fügen wir als neue Spalte <code>mean_var2</code> in den Datensatz ein:</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb245-1"><a href="5-7-anhang.html#cb245-1"></a><span class="kw">egen</span> mean_var2 = <span class="kw">mean</span>(var2)</span>
<span id="cb245-2"><a href="5-7-anhang.html#cb245-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2
## 1    1    2      4.75
## 2    2    4      4.75
## 3    7    7      4.75
## 4    8    6      4.75</code></pre>
<p><img src="Stata_Skript_files/figure-html/plot_mittelwe-1.png" width="80%" style="display: block; margin: auto;" />
Müssten wir eine Prognose für die Werte von <code>var2</code> abgeben, wäre das arith. Mittel eine gute Wahl. Die <strong>vorhergesagten Werte</strong> werden jeweils auf der Linie für das arith. Mittel liegen.</p>
<p><img src="Stata_Skript_files/figure-html/mittelw2-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="resid" class="section level3">
<h3><span class="header-section-number">5.7.2</span> Residuen</h3>
<p>Allerdings liegen wir mit dem arith. Mittel dann immer auch Stück daneben. Diese Abweichung zwischen dem tatsächlichen und dem vorhergesagten Wert wird als <strong>Residuum</strong> bezeichnet, in unserem Beispiel ist das jeweils die Differenz zwischen <code>var2</code> und <code>mean</code>:
<span class="math display">\[Residuum = beobachteter\, Wert \; - \; vorhergesagter\,Wert\]</span>
Als Formel wird das in der Regel wie folgt dargestellt:
<span class="math display">\[\epsilon_{\text{i}} = \text{y}_{i} - \hat{\text{y}}_{i}\]</span></p>
<p>Wir können also die Residuen als Differenz zwischen <code>var2</code> und <code>mean</code> berechnen und in <code>df</code> ablegen:</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb247-1"><a href="5-7-anhang.html#cb247-1"></a><span class="kw">gen</span> m_abw = var2 - mean_var2</span>
<span id="cb247-2"><a href="5-7-anhang.html#cb247-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw
## 1    1    2      4.75 -2.75
## 2    2    4      4.75 -0.75
## 3    7    7      4.75  2.25
## 4    8    6      4.75  1.25</code></pre>
<p><img src="Stata_Skript_files/figure-html/res_pl1-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Was bedeutet also ein negativer oder ein positiver Wert für das Residuum?<a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a></p>
<p>Die horizontale Linie für das arithm. Mittel ist aber sehr deutlich nicht die beste Methode, um die Werte für <code>var2</code> vorherzusagen. In der Graphik können wir deutlich sehen, dass die Werte “weiter links”, also mit geringeren Werten für <code>var1</code>, auch geringere Werte für <code>var2</code> aufweisen. Wir könnten also unseren Vorhersagefehler bzw. das <em>Residuum</em> minimieren indem wir die Linie drehen. Die Idee der Regressionsanalyse ist es dabei, die Residuuen zu minimieren. Was würde aber passieren wenn wir die Residuen aus der Mittelwertsvorhersage aufsummieren, um Sie dann zu minimieren?</p>
</div>
<div id="quad_res" class="section level3">
<h3><span class="header-section-number">5.7.3</span> Quadrierte Residuen</h3>
<p>Mit <code>tabstat ..., s(sum)</code> können wir die Summe für eine Variable bilden:</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb249-1"><a href="5-7-anhang.html#cb249-1"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw
## 1    1    2      4.75 -2.75
## 2    2    4      4.75 -0.75
## 3    7    7      4.75  2.25
## 4    8    6      4.75  1.25</code></pre>
<div class="sourceCode" id="cb251"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb251-1"><a href="5-7-anhang.html#cb251-1"></a><span class="kw">tabstat</span> m_abw, <span class="fu">s</span>(<span class="kw">sum</span>)</span></code></pre></div>
<pre><code>##  . use &quot;regression_bsp.dta&quot;, clear
## 
## . egen mean_var2 = mean(var2)
## 
## . gen m_abw = var2 - mean_var2
## 
## . tabstat m_abw, s(sum)
## 
##     variable |       sum
## -------------+----------
##        m_abw |         0
## ------------------------</code></pre>
<p><strong>Die Summe der Resiuden auf Basis des arith. Mittels ist immer Null!</strong><br />
Anders formuliert: die gestrichelten Linien nach oben sind in Summe genauso lang wie gestrichelten Linien nach unten.
Die Lösung ist die Residuen zu quadrieren. So ergibt sich eine Kennzahl, die wir minimieren können:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb253-1"><a href="5-7-anhang.html#cb253-1"></a><span class="kw">gen</span> m_abw2 = m_abw^2 </span>
<span id="cb253-2"><a href="5-7-anhang.html#cb253-2"></a><span class="kw">tabstat</span> m_abw2, <span class="fu">s</span>(<span class="kw">sum</span>)</span></code></pre></div>
<pre><code>##  . use &quot;regression_bsp.dta&quot;, clear
## 
## . egen mean_var2 = mean(var2)
## 
## . gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . predict pred_vorher, xb
## 
## . gen res = var2 - pred_vorher 
## 
## . gen res2 = res^2
## 
## . set linesize 90
## 
## . reg var2 var1
## 
##       Source |       SS       df       MS              Number of obs =       4
## -------------+------------------------------           F(  1,     2) =   11.07
##        Model |  12.4932432     1  12.4932432           Prob &gt; F      =  0.0797
##     Residual |  2.25675676     2  1.12837838           R-squared     =  0.8470
## -------------+------------------------------           Adj R-squared =  0.7705
##        Total |       14.75     3  4.91666667           Root MSE      =  1.0623
## 
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------
## 
## . gen m_abw2 = m_abw^2 
## 
## . tabstat m_abw2, s(sum)
## 
##     variable |       sum
## -------------+----------
##       m_abw2 |     14.75
## ------------------------</code></pre>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2
## 1    1    2      4.75 -2.75 7.5625
## 2    2    4      4.75 -0.75 0.5625
## 3    7    7      4.75  2.25 5.0625
## 4    8    6      4.75  1.25 1.5625</code></pre>
</div>
<div id="interpretation-der-regression" class="section level3">
<h3><span class="header-section-number">5.7.4</span> Interpretation der Regression</h3>
<p>Die Minimierung erledigt <code>reg</code> für uns. Hier geben wir zuerst das Merkmal an, das auf der y-Achse liegt (die <em>abhängige</em> Variable) und dann das Merkmal für die x-Achse (<em>unabhängige</em> Variable) an. Ein positiver Wert unter <code>Coef.</code> in der Zeile von <code>var1</code> bedeutet, dass unsere Gerade von links nach rechts ansteigt und ein negativer eine fallende Linie bedeuten würde. Der Wert unter <code>var1</code> gibt an, um <em>wieviel sich die Gerade pro “Schritt nach rechts” nach oben/unten verändert</em>. Die Gerade steigt also pro Einheit von <code>var1</code> um 0.5810811:</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb256-1"><a href="5-7-anhang.html#cb256-1"></a><span class="kw">reg</span> var2 var1</span></code></pre></div>
<pre><code>##  . use &quot;regression_bsp.dta&quot;, clear
## 
## . qui egen mean_var2 = mean(var2)
## 
## . qui gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . qui predict pred_vorher, xb
## 
## . qui gen res = var2 - pred_vorher 
## 
## . qui gen res2 = res^2
## 
## . qui set linesize 90
## 
## . reg var2 var1
## 
##       Source |       SS       df       MS              Number of obs =       4
## -------------+------------------------------           F(  1,     2) =   11.07
##        Model |  12.4932432     1  12.4932432           Prob &gt; F      =  0.0797
##     Residual |  2.25675676     2  1.12837838           R-squared     =  0.8470
## -------------+------------------------------           Adj R-squared =  0.7705
##        Total |       14.75     3  4.91666667           Root MSE      =  1.0623
## 
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------</code></pre>
<p>In unserer Grafik sieht diese Gerade so aus:
<img src="Stata_Skript_files/figure-html/unnamed-chunk-62-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="reg_pred" class="section level3">
<h3><span class="header-section-number">5.7.5</span> Vorhergesagte Werte</h3>
<p>Wie hoch ist nun der vorhergesagte Wert auf Basis der blauen Gerade?
Die vohergesagten Werte aus <code>reg var2 var1</code> entsprechen einfach der Summe aus dem Wert neben <code>_cons</code> und dem Koeffizienten neben <code>var1</code> multipliziert mit dem jeweiligen Wert für <code>var1</code>.<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a></p>
<div class="sourceCode" id="cb258"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb258-1"><a href="5-7-anhang.html#cb258-1"></a><span class="kw">reg</span> var2 var1, <span class="kw">noheader</span></span></code></pre></div>
<pre><code>##  . use &quot;regression_bsp.dta&quot;, clear
## 
## . qui egen mean_var2 = mean(var2)
## 
## . qui gen m_abw = var2 - mean_var2
## 
## . qui reg var2 var1
## 
## . qui predict pred_vorher, xb
## 
## . qui gen res = var2 - pred_vorher 
## 
## . qui gen res2 = res^2
## 
## . qui set linesize 90
## 
## . reg var2 var1, noheader
## ------------------------------------------------------------------------------
##         var2 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
## -------------+----------------------------------------------------------------
##         var1 |   .5810811   .1746331     3.33   0.080    -.1703044    1.332467
##        _cons |   2.135135   .9485004     2.25   0.153    -1.945933    6.216203
## ------------------------------------------------------------------------------</code></pre>
<p>Vorhergesagte Werte werden mit <span class="math inline">\(\widehat{var2}\)</span> bezeichnet - der ^ steht dabei für “vorhergesagt”:</p>
<p><span class="math display">\[\widehat{var2}=\texttt{Intercept} + 0.5811 \times \texttt{var1}\]</span><br />
Für die erste Zeile ergibt sich also folgender vorhergesagter Wert: 2.1351+0.5811*1= 2.7162</p>
<p>Also könnten wir mit <code>gen</code> die vorhergesagten Werte “manuell” berechnen:</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb260-1"><a href="5-7-anhang.html#cb260-1"></a><span class="kw">gen</span> manual_vorhers = 2.1351 + 0.5811 * var1</span></code></pre></div>
<p>Die vorhergesagten Werte können wir auch mit <code>predict</code> berechnen und in einer neuen Variable <code>pred_vorher</code> ablegen:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb261-1"><a href="5-7-anhang.html#cb261-1"></a><span class="kw">predict</span> pred_vorher, <span class="kw">xb</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2 manual_vorhers pred_vorher
## 1    1    2      4.75 -2.75 7.5625         2.7162    2.716216
## 2    2    4      4.75 -0.75 0.5625         3.2973    3.297297
## 3    7    7      4.75  2.25 5.0625         6.2028    6.202703
## 4    8    6      4.75  1.25 1.5625         6.7839    6.783784</code></pre>
<p>Die Grafik zeigt wie Vorhersagen auf Basis des Regressionsmodells aussehen: Sie entsprechen den Werten auf der blauen Geraden (der sog. Regressionsgeraden) an den jeweiligen Stellen für <code>var1</code>.
<img src="Stata_Skript_files/figure-html/unnamed-chunk-68-1.png" width="80%" style="display: block; margin: auto;" />
Wir können erkennen, dass die hellblauen Punkte (also die Vorhersagen des Regressionsmodells) deutlich näher an den tatsächlichen Punkten liegen als die orangen Vorhersagen auf Basis des <code>mean</code>.</p>
</div>
<div id="resid2" class="section level3">
<h3><span class="header-section-number">5.7.6</span> Residuen Teil 2</h3>
<p>Trotzdem sind auch die hellblauen Punkte nicht deckungsgleich mit den tatsächlichen Werten. Es gibt also auch hier wieder <a href="5-7-anhang.html#resid">Residuen</a>, also Abweichungen des beobachteten vom vorhergesagten Wert. Wir können diese per Hand berechnen als Differenz zwischen dem tatsächlichen und dem vorhergesagten Wert:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb263-1"><a href="5-7-anhang.html#cb263-1"></a><span class="kw">gen</span> res = var2 - pred_vorher </span></code></pre></div>
<p>Oder wir können Sie mit <code>predict neue_variable , residuals</code> erstellen:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb264-1"><a href="5-7-anhang.html#cb264-1"></a><span class="kw">reg</span> var2 var1 <span class="co">// zunächst nochmal die regression laufen lassen</span></span>
<span id="cb264-2"><a href="5-7-anhang.html#cb264-2"></a><span class="kw">predict</span> p_res , residuals</span>
<span id="cb264-3"><a href="5-7-anhang.html#cb264-3"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2 manual_vorhers pred_vorher        res      p_res
## 1    1    2      4.75 -2.75 7.5625         2.7162    2.716216 -0.7162162 -0.7162162
## 2    2    4      4.75 -0.75 0.5625         3.2973    3.297297  0.7027027  0.7027027
## 3    7    7      4.75  2.25 5.0625         6.2028    6.202703  0.7972973  0.7972973
## 4    8    6      4.75  1.25 1.5625         6.7839    6.783784 -0.7837838 -0.7837838</code></pre>
<p>Hier sind die Residuen für <code>p_res</code> als hellblaue Linien eingezeichnet:
<img src="Stata_Skript_files/figure-html/unnamed-chunk-72-1.png" width="80%" style="display: block; margin: auto;" />
<span class="math inline">\(\rightarrow\)</span> <em>Wie groß ist die (einfache) Summe der Residuen für <code>pred_vorher</code>?</em><a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a></p>
</div>
<div id="r2" class="section level3">
<h3><span class="header-section-number">5.7.7</span> Modellgüte</h3>
<p>Um zu beurteilen, um wieviel besser unsere Gerade aus <code>reg</code> die Werte vorhersagen kann als der <code>mean</code> können wir die Summe der quadrierten Residuen vergleichen. Dazu quadrieren wir also die Residuen:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb266-1"><a href="5-7-anhang.html#cb266-1"></a><span class="kw">gen</span> res2 = res^2</span>
<span id="cb266-2"><a href="5-7-anhang.html#cb266-2"></a><span class="ot">list</span></span></code></pre></div>
<pre><code>##   var1 var2 mean_var2 m_abw m_abw2 manual_vorhers pred_vorher        res      res2
## 1    1    2      4.75 -2.75 7.5625         2.7162    2.716216 -0.7162162 0.5129657
## 2    2    4      4.75 -0.75 0.5625         3.2973    3.297297  0.7027027 0.4937911
## 3    7    7      4.75  2.25 5.0625         6.2028    6.202703  0.7972973 0.6356830
## 4    8    6      4.75  1.25 1.5625         6.7839    6.783784 -0.7837838 0.6143170</code></pre>
<p>Dann können wir die Summen der quadierten Abweichungen aus der Mittelwertregel und dem Regressionsmodell vergleichen:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb268-1"><a href="5-7-anhang.html#cb268-1"></a>dis 7.5625+0.5625+5.0625+1.5625 <span class="co">// abw2 aus Mittelwertsregel</span></span>
<span id="cb268-2"><a href="5-7-anhang.html#cb268-2"></a>##  . dis 7.5625+0.5625+5.0625+1.5625 <span class="co">// abw2 aus Mittelwertsregel</span></span>
<span id="cb268-3"><a href="5-7-anhang.html#cb268-3"></a>## 14.75</span></code></pre></div>
<div class="sourceCode" id="cb269"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb269-1"><a href="5-7-anhang.html#cb269-1"></a>dis 0.5129657+0.4937911+0.6356830+0.6143170 <span class="co">// res2 aus regressionsmodell</span></span>
<span id="cb269-2"><a href="5-7-anhang.html#cb269-2"></a>##  . dis 0.5129657+0.4937911+0.6356830+0.6143170 <span class="co">// res2 aus regressionsmodell</span></span>
<span id="cb269-3"><a href="5-7-anhang.html#cb269-3"></a>## 2.2567568</span></code></pre></div>
<p>Zum Beispiel können wir uns fragen, um wieviel sich die Summe der quadrierten Residuen verringert wenn wir statt des <code>mean</code> unser <code>reg</code>-Modell verwenden:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb270-1"><a href="5-7-anhang.html#cb270-1"></a>dis 14.75 -  2.256757</span>
<span id="cb270-2"><a href="5-7-anhang.html#cb270-2"></a>##  . dis 14.75 -  2.256757</span>
<span id="cb270-3"><a href="5-7-anhang.html#cb270-3"></a>## 12.493243</span></code></pre></div>
<p>Wenn wir diese Veränderung ins Verhältnis mit dem “Ausgangswert”, also den Residuen aus der Mittelwertregel setzen, dann erhalten wir das <span class="math inline">\(R^{2}\)</span> für unser <code>reg</code>-Modell. Dieses gibt die prozentuale Verringerung der Residuen durch das <code>reg</code>-Modell im Vergleich zur Mittelwertregel an:</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb271-1"><a href="5-7-anhang.html#cb271-1"></a>dis (14.75 -  2.256757) / 14.75</span>
<span id="cb271-2"><a href="5-7-anhang.html#cb271-2"></a>##  . dis (14.75 -  2.256757) / 14.75</span>
<span id="cb271-3"><a href="5-7-anhang.html#cb271-3"></a>## .84699953</span></code></pre></div>
<p>Unser Regressionsmodell kann also 84,7% der Streuung um den Mittelwert erklären. Dieser Wert wird auch als <span class="math inline">\(R^2\)</span> bezeichnet. Im Regressionsoutput können wir das <span class="math inline">\(R^2\)</span> oben rechts unter <code>R-squared</code> ablesen.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb272-1"><a href="5-7-anhang.html#cb272-1"></a><span class="kw">reg</span> var2 var1</span>
<span id="cb272-2"><a href="5-7-anhang.html#cb272-2"></a>##  . <span class="kw">reg</span> var2 var1</span>
<span id="cb272-3"><a href="5-7-anhang.html#cb272-3"></a>## no variables defined</span>
<span id="cb272-4"><a href="5-7-anhang.html#cb272-4"></a>## <span class="fu">r</span>(111);</span>
<span id="cb272-5"><a href="5-7-anhang.html#cb272-5"></a>## </span>
<span id="cb272-6"><a href="5-7-anhang.html#cb272-6"></a>## <span class="kw">end</span> <span class="kw">of</span> <span class="kw">do</span>-file</span>
<span id="cb272-7"><a href="5-7-anhang.html#cb272-7"></a>## <span class="fu">r</span>(111);</span></code></pre></div>
<p>Außerdem sehen wir oben links in der Spalte <code>SS</code> die “Sum of Squares”. Hier finden wir auch die Werte von oben wieder: unter Total ist die Summe der quadrierten Abweichungen der beobachteten Werte vom arith. Mittel angegeben (<code>14.75</code>, sozusagen die Summe der <code>m_abw2</code> von oben). Residual gibt die Summe der Abweichungsquadrate zwischen den beobachteten Werten und den vorhergesagten Werten der Regression (<code>2.256..</code>, Die Summe von <code>res2</code>).</p>
</div>
<div id="indiff" class="section level3">
<h3><span class="header-section-number">5.7.8</span> Indifferenztabelle</h3>
<p><span class="math inline">\(\chi^2\)</span> ergibt sich wie gesagt aus der Differenz zwischen der Indifferenztabelle und den beobachteten Häufigkeiten. Die Indifferenztabelle können wir mit <code>,expected</code> aufrufen (mit <code>nofreq</code> blenden wir die tatsächlichen Häufigkeiten aus):</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb273-1"><a href="5-7-anhang.html#cb273-1"></a><span class="kw">tab</span>  aq03  dh01, expected nofreq</span></code></pre></div>
<pre><code>##  . set linesize 90
## 
## . qui cd &quot;D:\Studium\01_Oldenburg\Lehre\Datensaetze&quot;
## 
## . qui use  &quot;Allbus_1980-2018.dta&quot;,clear
## 
## . qui keep if year == 2014 &amp; dh01 &gt; 0 &amp; dh04 &gt; 0 &amp; aq03 &gt; 0
## 
## . qui mvdecode aq03 dh01 dh04, mv(-32 -9)
## 
## . tab aq03 dh01, expected nofreq
## 
##  HUND ODER KATZE | MEHRPERSONENHAUSHALT?
##     IM HAUSHALT? | MEHRPERSO  EINPERSON |     Total
## -----------------+----------------------+----------
##             HUND |     312.3       78.7 |     391.0 
##            KATZE |     452.8      114.2 |     567.0 
##           BEIDES |      99.8       25.2 |     125.0 
## KEINS VON BEIDEN |   1,887.1      475.9 |   2,363.0 
## -----------------+----------------------+----------
##            Total |   2,752.0      694.0 |   3,446.0</code></pre>
<p>Ausgangspunkt für diese Indifferenztabelle sind die relativen Häufigkeiten der tatsächlich beoachteten Werte:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb275-1"><a href="5-7-anhang.html#cb275-1"></a><span class="kw">tab</span>  aq03  dh01, cell nofreq</span></code></pre></div>
<pre><code>##  . set linesize 90
## 
## . qui cd &quot;D:\Studium\01_Oldenburg\Lehre\Datensaetze&quot;
## 
## . qui use  &quot;Allbus_1980-2018.dta&quot;,clear
## 
## . qui keep if year == 2014 &amp; dh01 &gt; 0 &amp; dh04 &gt; 0 &amp; aq03 &gt; 0
## 
## . qui mvdecode aq03 dh01 dh04, mv(-32 -9)
## 
## . tab aq03 dh01,cell nofreq
## 
##  HUND ODER KATZE | MEHRPERSONENHAUSHALT?
##     IM HAUSHALT? | MEHRPERSO  EINPERSON |     Total
## -----------------+----------------------+----------
##             HUND |     10.16       1.19 |     11.35 
##            KATZE |     14.57       1.89 |     16.45 
##           BEIDES |      3.37       0.26 |      3.63 
## KEINS VON BEIDEN |     51.77      16.80 |     68.57 
## -----------------+----------------------+----------
##            Total |     79.86      20.14 |    100.00</code></pre>
<p>0.26 % der Befragten wohnen alleine (<code>dh01</code> = 2) und haben einen Hund und eine Katze (<code>aq03</code>=3).<br />
Uns interessieren hier nur die Randverteilungen aus <code>Sum</code>: 3.63 % der Befragten haben einen Hund und eine Katze (<code>aq03</code>=3). 20.14 % der Befragten wohnen alleine (<code>dh01</code> = 2).</p>
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
MEHRPERSO
</th>
<th style="text-align:left;">
EINPERSON
</th>
<th style="text-align:left;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
HUND
</td>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
E
</td>
<td style="text-align:left;">
0.1135
</td>
</tr>
<tr>
<td style="text-align:left;">
KATZE
</td>
<td style="text-align:left;">
B
</td>
<td style="text-align:left;">
F
</td>
<td style="text-align:left;">
0.1645
</td>
</tr>
<tr>
<td style="text-align:left;">
BEIDES
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:left;">
G
</td>
<td style="text-align:left;">
0.0363
</td>
</tr>
<tr>
<td style="text-align:left;">
KEINES VON BEIDEM
</td>
<td style="text-align:left;">
D
</td>
<td style="text-align:left;">
H
</td>
<td style="text-align:left;">
0.6857
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
0.7986
</td>
<td style="text-align:left;">
0.2014
</td>
<td style="text-align:left;">
1
</td>
</tr>
</tbody>
</table>
<p>Wären beide Merkmale unabhängig voneinander, würden wir erwarten, dass die Wahrscheinlichkeit für das Auftreten einer Merkmalskombination dem Produkt der Einzelwahrscheinlichkeiten entspricht (das ist die “Indifferenz”): <span class="math inline">\(P(A\cup B) = P(A) \times P(B)\)</span>. Bspw. ergibt sich der erwartete Wert für die Zellen dann aus der relativen Randverteilung multipliziert mit der Gesamtfallzahl:</p>
<ul>
<li><p>für Zelle <code>B</code>: <code>0.1645</code> <span class="math inline">\(\times\)</span> <code>0.7986</code> <span class="math inline">\(\times\)</span> 3446 = 452.8102.</p></li>
<li><p>für Zelle <code>C</code>: <code>0.0363</code> <span class="math inline">\(\times\)</span> <code>0.7986</code> <span class="math inline">\(\times\)</span> 3446 = 99.8259.</p></li>
<li><p>für Zelle <code>H</code>: <code>0.6857</code> <span class="math inline">\(\times\)</span> <code>0.2014</code> <span class="math inline">\(\times\)</span> 3446 = 475.8915.</p></li>
</ul>
<p>Dies sind auch die Werte, die Stata uns oben mit <code>tab  aq03  dh01, expected nofreq</code> ausgegeben hatte.</p>
<p><span class="math inline">\(\chi^2\)</span> ist dann die summierte Differenz zwischen dieser Indifferenztabelle (also der erwarteten Verteilung bei Unabhängigkeit beider Merkmale) und den beobachteten Häufigkeiten: je größer die Differenz, desto unwahrscheinlicher ist es, dass beide Merkmale unabhängig sind.</p>

</div>
</div>
<!-- </div> -->
<div class="footnotes">
<hr />
<ol start="15">
<li id="fn15"><p>Mehr zu <code>egen</code> in Kapitel <a href="11-4-egen.html#egen">11.4</a><a href="5-7-anhang.html#fnref15" class="footnote-back">↩︎</a></p></li>
<li id="fn16"><p>Ein positiver Wert des Residuums bedeutet, dass der beobachtete Wert größer als der vorhergesagte Wert ist. Die Regressionsgerade <em>unterschätzt</em> also den Wert. Ein negatives Residuum bedeutet dementsprechend, dass die Regressionsgerade den Wert überschätzt - der wahre Wert ist niedriger als der vorhergesagte Wert. Siehe <a href="5-7-anhang.html#resid">Formeln</a><a href="5-7-anhang.html#fnref16" class="footnote-back">↩︎</a></p></li>
<li id="fn17"><p>Die Option <code>noheader</code> macht den Output von <code>reg</code> etwas übersichtlicher.<a href="5-7-anhang.html#fnref17" class="footnote-back">↩︎</a></p></li>
<li id="fn18"><p>Die (einfache, unquadrierte) Summe der Resiuden beträgt auch hier Null.<a href="5-7-anhang.html#fnref18" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<p style="text-align: center;">
<a href="5-6-profi-übungen-5.html"><button class="btn btn-default">Previous</button></a>
<a href="6-zshg2.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
