<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="7.5 Anhang Kap7 | GESIS Methodenseminar 2020" />
<meta property="og:type" content="book" />


<meta property="og:description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020" />


<meta name="author" content="Andreas Filser" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020">

<title>7.5 Anhang Kap7 | GESIS Methodenseminar 2020</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#herzlich-willkommen">Herzlich Willkommen!</a></li>
<li class="has-sub"><a href="1-Stata1.html#Stata1"><span class="toc-section-number">1</span> Einstieg in Stata</a><ul>
<li><a href="1-1-taschenrechner.html#taschenrechner"><span class="toc-section-number">1.1</span> Taschenrechner</a></li>
<li><a href="1-2-darstellung-in-diesem-skript.html#darstellung-in-diesem-skript"><span class="toc-section-number">1.2</span> Darstellung in diesem Skript</a></li>
<li><a href="1-3-dofile-editor.html#dofile-editor"><span class="toc-section-number">1.3</span> DoFile Editor</a></li>
<li><a href="1-4-datensätze-laden.html#datensätze-laden"><span class="toc-section-number">1.4</span> Datensätze laden</a></li>
<li><a href="1-5-daten-codebücher-fragebogen.html#daten-codebücher-fragebogen"><span class="toc-section-number">1.5</span> Daten, Codebücher, Fragebogen</a></li>
<li class="has-sub"><a href="1-6-überblicksbefehle.html#überblicksbefehle"><span class="toc-section-number">1.6</span> Überblicksbefehle</a><ul>
<li><a href="1-6-überblicksbefehle.html#describe"><span class="toc-section-number">1.6.1</span> <code>describe</code></a></li>
<li><a href="1-6-überblicksbefehle.html#browse"><span class="toc-section-number">1.6.2</span> <code>browse</code></a></li>
<li><a href="1-6-überblicksbefehle.html#list"><span class="toc-section-number">1.6.3</span> <code>list</code></a></li>
<li><a href="1-6-überblicksbefehle.html#lookfor"><span class="toc-section-number">1.6.4</span> <code>lookfor</code></a></li>
</ul></li>
<li><a href="1-7-löschen.html#löschen"><span class="toc-section-number">1.7</span> löschen</a></li>
<li><a href="1-8-if-bedingung-nur-manche-zeilen-ansehen.html#if-bedingung---nur-manche-zeilen-ansehen"><span class="toc-section-number">1.8</span> if Bedingung - nur manche Zeilen ansehen</a></li>
<li><a href="1-9-U1.html#U1"><span class="toc-section-number">1.9</span> Übungen 1</a></li>
<li><a href="1-10-profi-übungen-1.html#profi-übungen-1"><span class="toc-section-number">1.10</span> Profi-Übungen 1</a></li>
<li class="has-sub"><a href="1-11-anhang-1.html#anhang-1"><span class="toc-section-number">1.11</span> Anhang 1</a><ul>
<li><a href="1-11-anhang-1.html#var_types"><span class="toc-section-number">1.11.1</span> Variablentypen</a></li>
<li><a href="1-11-anhang-1.html#otherfmts"><span class="toc-section-number">1.11.2</span> import anderer Dateiformate</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="2-Stata2.html#Stata2"><span class="toc-section-number">2</span> Arbeiten mit Datensätzen in Stata</a><ul>
<li><a href="2-1-vorab-befehlsstruktur-hilfe.html#vorab-befehlsstruktur-hilfe"><span class="toc-section-number">2.1</span> Vorab: Befehlsstruktur &amp; Hilfe</a></li>
<li><a href="2-2-auszählen-überblick-erhalten.html#auszählen-überblick-erhalten"><span class="toc-section-number">2.2</span> Auszählen &amp; Überblick erhalten</a></li>
<li><a href="2-3-neue-variablen-erstellen.html#neue-variablen-erstellen"><span class="toc-section-number">2.3</span> Neue Variablen erstellen</a></li>
<li><a href="2-4-bestehende-variablen-verändern.html#bestehende-variablen-verändern"><span class="toc-section-number">2.4</span> Bestehende Variablen verändern</a></li>
<li><a href="2-5-gen-ist-gut-kontrolle-ist-besser.html#gen-ist-gut-kontrolle-ist-besser"><span class="toc-section-number">2.5</span> gen ist gut, Kontrolle ist besser</a></li>
<li><a href="2-6-fehlende-werte.html#fehlende-werte"><span class="toc-section-number">2.6</span> Fehlende Werte</a></li>
<li><a href="2-7-if-bedingungen-und-fehlende-werte.html#if-bedingungen-und-fehlende-werte"><span class="toc-section-number">2.7</span> if Bedingungen und fehlende Werte</a></li>
<li><a href="2-8-keep-drop.html#keep-drop"><span class="toc-section-number">2.8</span> keep &amp; drop</a></li>
<li><a href="2-9-labels-und-if-bedingungen.html#labels-und-if-bedingungen"><span class="toc-section-number">2.9</span> Labels und if-Bedingungen</a></li>
<li><a href="2-10-nochmal-von-vorne-daten-neu-laden.html#nochmal-von-vorne-daten-neu-laden"><span class="toc-section-number">2.10</span> Nochmal von vorne: Daten neu laden</a></li>
<li><a href="2-11-speichern.html#speichern"><span class="toc-section-number">2.11</span> Speichern</a></li>
<li><a href="2-12-übungen-2.html#übungen-2"><span class="toc-section-number">2.12</span> Übungen 2</a></li>
<li><a href="2-13-profi-übungen-2.html#profi-übungen-2"><span class="toc-section-number">2.13</span> Profi-Übungen 2</a></li>
</ul></li>
<li class="has-sub"><a href="3-desc1.html#desc1"><span class="toc-section-number">3</span> Deskriptive Statistik</a><ul>
<li class="has-sub"><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#kategoriale-merkmale-mit-tabulate-beschreiben"><span class="toc-section-number">3.1</span> Kategoriale Merkmale mit <code>tabulate</code> beschreiben</a><ul>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#zwei-variablen-eine-tabelle-kontingenztabellen"><span class="toc-section-number">3.1.1</span> Zwei Variablen, eine Tabelle: Kontingenztabellen</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#in-prozent-relative-häufigkeiten"><span class="toc-section-number">3.1.2</span> In Prozent: Relative Häufigkeiten</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-1-zeilenprozente"><span class="toc-section-number">3.1.3</span> pro Gruppe 1: Zeilenprozente</a></li>
<li><a href="3-1-kategoriale-merkmale-mit-tabulate-beschreiben.html#pro-gruppe-2-spaltenprozente"><span class="toc-section-number">3.1.4</span> pro Gruppe 2: Spaltenprozente</a></li>
</ul></li>
<li class="has-sub"><a href="3-2-metrische-variablen-beschreiben.html#metrische-variablen-beschreiben"><span class="toc-section-number">3.2</span> Metrische Variablen beschreiben</a><ul>
<li><a href="3-2-metrische-variablen-beschreiben.html#summarize"><span class="toc-section-number">3.2.1</span> <code>summarize</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#tabstat"><span class="toc-section-number">3.2.2</span> <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#by_vgl"><span class="toc-section-number">3.2.3</span> Kennzahlen vergleichen mit <code>tabstat</code></a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#streu"><span class="toc-section-number">3.2.4</span> Streuungsmaße: Varianz, Standardabweichung, Variationskoeffizient</a></li>
<li><a href="3-2-metrische-variablen-beschreiben.html#gini-koeffizient"><span class="toc-section-number">3.2.5</span> Gini-Koeffizient</a></li>
</ul></li>
<li class="has-sub"><a href="3-3-übungen-3.html#übungen-3"><span class="toc-section-number">3.3</span> Übungen 3</a><ul>
<li><a href="3-3-übungen-3.html#tab"><span class="toc-section-number">3.3.1</span> Übung 3-1</a></li>
<li><a href="3-3-übungen-3.html#met"><span class="toc-section-number">3.3.2</span> Übung 3-2</a></li>
<li><a href="3-3-übungen-3.html#weitere-übungen-3"><span class="toc-section-number">3.3.3</span> Weitere Übungen 3</a></li>
</ul></li>
<li><a href="3-4-profi-übungen-3.html#profi-übungen-3"><span class="toc-section-number">3.4</span> Profi-Übungen 3</a></li>
<li class="has-sub"><a href="3-5-anhang-kap-3.html#anhang-kap-3"><span class="toc-section-number">3.5</span> Anhang Kap 3</a><ul>
<li><a href="3-5-anhang-kap-3.html#vlabel"><span class="toc-section-number">3.5.1</span> labels vergeben</a></li>
<li><a href="3-5-anhang-kap-3.html#variance"><span class="toc-section-number">3.5.2</span> Varianz erklärt</a></li>
<li><a href="3-5-anhang-kap-3.html#sk_kur"><span class="toc-section-number">3.5.3</span> Schiefe &amp; Wölbung</a></li>
<li><a href="3-5-anhang-kap-3.html#bys_su"><span class="toc-section-number">3.5.4</span> Kombination von <code>summarize</code> mit dem <code>by</code>-Präfix</a></li>
<li><a href="3-5-anhang-kap-3.html#if_vgl"><span class="toc-section-number">3.5.5</span> Kennzahlvergleiche mit <code>if</code></a></li>
<li><a href="3-5-anhang-kap-3.html#kennzahlvergleich-mit-tabulate-und-der-option-summarize"><span class="toc-section-number">3.5.6</span> Kennzahlvergleich mit <code>tabulate</code> und der Option <code>summarize()</code></a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="4-dataviz.html#dataviz"><span class="toc-section-number">4</span> Datenvisualisierung in Stata</a><ul>
<li class="has-sub"><a href="4-1-visualisierung-einer-variable.html#visualisierung-einer-variable"><span class="toc-section-number">4.1</span> Visualisierung einer Variable</a><ul>
<li><a href="4-1-visualisierung-einer-variable.html#metrische-variablen"><span class="toc-section-number">4.1.1</span> metrische Variablen</a></li>
<li><a href="4-1-visualisierung-einer-variable.html#bar_col"><span class="toc-section-number">4.1.2</span> Kategoriale Variablen</a></li>
</ul></li>
<li><a href="4-2-verteilungen-vergleichen-mit-facetten.html#verteilungen-vergleichen-mit-facetten"><span class="toc-section-number">4.2</span> Verteilungen vergleichen mit Facetten</a></li>
<li class="has-sub"><a href="4-3-bivar-plot.html#bivar_plot"><span class="toc-section-number">4.3</span> Gemeinsame Verteilung zweier Variablen</a><ul>
<li><a href="4-3-bivar-plot.html#mosaikplot"><span class="toc-section-number">4.3.1</span> Mosaikplot</a></li>
<li><a href="4-3-bivar-plot.html#streudiagramm"><span class="toc-section-number">4.3.2</span> Streudiagramm</a></li>
</ul></li>
<li><a href="4-4-weitere-twoway-grafiken.html#weitere-twoway-grafiken"><span class="toc-section-number">4.4</span> Weitere <code>twoway</code> Grafiken</a></li>
<li><a href="4-5-twoway-comb.html#twoway_comb"><span class="toc-section-number">4.5</span> Kombinieren von zwei twoway-Grafiken</a></li>
<li><a href="4-6-gruppierte-boxplots.html#gruppierte-boxplots"><span class="toc-section-number">4.6</span> Gruppierte Boxplots</a></li>
<li class="has-sub"><a href="4-7-übungen-4.html#übungen-4"><span class="toc-section-number">4.7</span> Übungen 4</a><ul>
<li><a href="4-7-übungen-4.html#plt1"><span class="toc-section-number">4.7.1</span> Übung 4-1</a></li>
<li><a href="4-7-übungen-4.html#plt2"><span class="toc-section-number">4.7.2</span> Übung 4-2</a></li>
<li><a href="4-7-übungen-4.html#weitere-übungen-kap4"><span class="toc-section-number">4.7.3</span> Weitere Übungen Kap4</a></li>
</ul></li>
<li class="has-sub"><a href="4-8-optionen.html#optionen"><span class="toc-section-number">4.8</span> Optionen</a><ul>
<li><a href="4-8-optionen.html#title"><span class="toc-section-number">4.8.1</span> Titel</a></li>
<li><a href="4-8-optionen.html#achsenbeschriftung"><span class="toc-section-number">4.8.2</span> Achsenbeschriftung</a></li>
<li><a href="4-8-optionen.html#text-einfügen"><span class="toc-section-number">4.8.3</span> Text einfügen</a></li>
<li><a href="4-8-optionen.html#font"><span class="toc-section-number">4.8.4</span> Schriftart &amp; Textgröße</a></li>
<li><a href="4-8-optionen.html#legend"><span class="toc-section-number">4.8.5</span> Legende</a></li>
<li><a href="4-8-optionen.html#mark"><span class="toc-section-number">4.8.6</span> Marker</a></li>
<li><a href="4-8-optionen.html#color"><span class="toc-section-number">4.8.7</span> Farben</a></li>
<li><a href="4-8-optionen.html#vorlagen"><span class="toc-section-number">4.8.8</span> Vorlagen</a></li>
</ul></li>
<li class="has-sub"><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#anhang-beispiele-zum-selbst-anpassen"><span class="toc-section-number">4.9</span> Anhang &amp; Beispiele zum selbst anpassen</a><ul>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#boxplot"><span class="toc-section-number">4.9.1</span> Boxplot</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#scatterplot"><span class="toc-section-number">4.9.2</span> Scatterplot</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#pyramid"><span class="toc-section-number">4.9.3</span> Bevölkerungspyramide</a></li>
<li><a href="4-9-anhang-beispiele-zum-selbst-anpassen.html#boxplot1"><span class="toc-section-number">4.9.4</span> Boxplot</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="5-zshg.html#zshg"><span class="toc-section-number">5</span> Zusammenhangsmaße</a><ul>
<li class="has-sub"><a href="5-1-zshg-met.html#zshg_met"><span class="toc-section-number">5.1</span> Metrisch skalierte Variablen</a><ul>
<li><a href="5-1-zshg-met.html#cor"><span class="toc-section-number">5.1.1</span> Korrelationskoeffizient</a></li>
<li><a href="5-1-zshg-met.html#regression"><span class="toc-section-number">5.1.2</span> Regression</a></li>
<li><a href="5-1-zshg-met.html#vorhergesagte-werte"><span class="toc-section-number">5.1.3</span> vorhergesagte Werte</a></li>
</ul></li>
<li class="has-sub"><a href="5-2-zshg-ord.html#zshg_ord"><span class="toc-section-number">5.2</span> Ordinal skalierte Merkmale</a><ul>
<li><a href="5-2-zshg-ord.html#spear"><span class="toc-section-number">5.2.1</span> Spearman- Rangkorrelation</a></li>
<li><a href="5-2-zshg-ord.html#tau"><span class="toc-section-number">5.2.2</span> Konkordanzmaße</a></li>
</ul></li>
<li class="has-sub"><a href="5-3-zshg-nom.html#zshg_nom"><span class="toc-section-number">5.3</span> Nominal skalierte Variablen</a><ul>
<li><a href="5-3-zshg-nom.html#OR"><span class="toc-section-number">5.3.1</span> Odds Ratio</a></li>
<li><a href="5-3-zshg-nom.html#chi2"><span class="toc-section-number">5.3.2</span> Chi²-basierte Maße</a></li>
<li><a href="5-3-zshg-nom.html#cramers-upsilon"><span class="toc-section-number">5.3.3</span> Cramer’s <span class="math inline">\(\upsilon\)</span></a></li>
<li><a href="5-3-zshg-nom.html#phi"><span class="toc-section-number">5.3.4</span> <span class="math inline">\(\phi\)</span></a></li>
</ul></li>
<li><a href="5-4-welches-maß-richtig.html#welches-maß-richtig"><span class="toc-section-number">5.4</span> Welches Maß richtig?</a></li>
<li class="has-sub"><a href="5-5-übungen-5.html#übungen-5"><span class="toc-section-number">5.5</span> Übungen 5</a><ul>
<li><a href="5-5-übungen-5.html#auf_met"><span class="toc-section-number">5.5.1</span> Übung 5-1</a></li>
<li><a href="5-5-übungen-5.html#auf_ord"><span class="toc-section-number">5.5.2</span> Übung 5-2</a></li>
<li><a href="5-5-übungen-5.html#auf_nom"><span class="toc-section-number">5.5.3</span> Übung 5-3</a></li>
<li><a href="5-5-übungen-5.html#weitere-übungen-5"><span class="toc-section-number">5.5.4</span> Weitere Übungen 5</a></li>
</ul></li>
<li><a href="5-6-profi-übungen-5.html#profi-übungen-5"><span class="toc-section-number">5.6</span> Profi-Übungen 5</a></li>
<li class="has-sub"><a href="5-7-anhang.html#anhang"><span class="toc-section-number">5.7</span> Anhang</a><ul>
<li><a href="5-7-anhang.html#reg"><span class="toc-section-number">5.7.1</span> Idee einer Regression</a></li>
<li><a href="5-7-anhang.html#resid"><span class="toc-section-number">5.7.2</span> Residuen</a></li>
<li><a href="5-7-anhang.html#quad_res"><span class="toc-section-number">5.7.3</span> Quadrierte Residuen</a></li>
<li><a href="5-7-anhang.html#interpretation-der-regression"><span class="toc-section-number">5.7.4</span> Interpretation der Regression</a></li>
<li><a href="5-7-anhang.html#reg_pred"><span class="toc-section-number">5.7.5</span> Vorhergesagte Werte</a></li>
<li><a href="5-7-anhang.html#resid2"><span class="toc-section-number">5.7.6</span> Residuen Teil 2</a></li>
<li><a href="5-7-anhang.html#r2"><span class="toc-section-number">5.7.7</span> Modellgüte</a></li>
<li><a href="5-7-anhang.html#indiff"><span class="toc-section-number">5.7.8</span> Indifferenztabelle</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="6-zshg2.html#zshg2"><span class="toc-section-number">6</span> Zusammenhänge 2</a><ul>
<li><a href="6-1-zusammenhänge-vergleichen.html#zusammenhänge-vergleichen"><span class="toc-section-number">6.1</span> Zusammenhänge vergleichen</a></li>
<li><a href="6-2-zusammenhänge-visualisieren.html#zusammenhänge-visualisieren"><span class="toc-section-number">6.2</span> Zusammenhänge visualisieren</a></li>
<li class="has-sub"><a href="6-3-kategoriale-zusammenhänge.html#kategoriale-zusammenhänge"><span class="toc-section-number">6.3</span> Kategoriale Zusammenhänge</a><ul>
<li><a href="6-3-kategoriale-zusammenhänge.html#ordinale-zusammenhangsmaße-vergleichen"><span class="toc-section-number">6.3.1</span> Ordinale Zusammenhangsmaße vergleichen</a></li>
<li><a href="6-3-kategoriale-zusammenhänge.html#vergleich-visualisieren"><span class="toc-section-number">6.3.2</span> Vergleich visualisieren</a></li>
<li><a href="6-3-kategoriale-zusammenhänge.html#nominale-zusammenhangsmaße-vergleichen"><span class="toc-section-number">6.3.3</span> Nominale Zusammenhangsmaße vergleichen</a></li>
</ul></li>
<li class="has-sub"><a href="6-4-übungen-6.html#übungen-6"><span class="toc-section-number">6.4</span> Übungen 6</a><ul>
<li><a href="6-4-übungen-6.html#met_vgl"><span class="toc-section-number">6.4.1</span> Übung 6-1</a></li>
<li><a href="6-4-übungen-6.html#ord_vgl"><span class="toc-section-number">6.4.2</span> Übung 6-2</a></li>
<li><a href="6-4-übungen-6.html#nom_vgl"><span class="toc-section-number">6.4.3</span> Übung 6-3</a></li>
<li><a href="6-4-übungen-6.html#weitere-übungen-kap-6"><span class="toc-section-number">6.4.4</span> Weitere Übungen Kap 6</a></li>
</ul></li>
<li class="has-sub"><a href="5-7-anhang.html#anhang"><span class="toc-section-number">6.5</span> Anhang</a><ul>
<li><a href="6-5-anhang.html#lpattern"><span class="toc-section-number">6.5.1</span> Optionen für <code>lpattern</code></a></li>
<li><a href="6-5-anhang.html#scatterplot-für-kategoriale-merkmale"><span class="toc-section-number">6.5.2</span> Scatterplot für kategoriale Merkmale</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="7-inf1.html#inf1"><span class="toc-section-number">7</span> Inferenzstatistik I</a><ul>
<li><a href="7-1-inferenz.html#inferenz"><span class="toc-section-number">7.1</span> Inferenz</a></li>
<li class="has-sub"><a href="7-2-parametrische-ki-schätzung.html#parametrische-ki-schätzung"><span class="toc-section-number">7.2</span> Parametrische KI-Schätzung</a><ul>
<li><a href="7-2-parametrische-ki-schätzung.html#t-z-wert"><span class="toc-section-number">7.2.1</span> t-/z-Wert</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#standardfehler"><span class="toc-section-number">7.2.2</span> Standardfehler</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#kis-berechnen"><span class="toc-section-number">7.2.3</span> KIs berechnen</a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#mean"><span class="toc-section-number">7.2.4</span> <code>mean</code></a></li>
<li><a href="7-2-parametrische-ki-schätzung.html#vergleich"><span class="toc-section-number">7.2.5</span> Vergleich</a></li>
</ul></li>
<li><a href="7-3-bootstrapping.html#bootstrapping"><span class="toc-section-number">7.3</span> Bootstrapping</a></li>
<li><a href="7-4-übungen-7.html#übungen-7"><span class="toc-section-number">7.4</span> Übungen 7</a></li>
<li class="has-sub"><a href="7-5-anhang-kap7.html#anhang-kap7"><span class="toc-section-number">7.5</span> Anhang Kap7</a><ul>
<li><a href="7-5-anhang-kap7.html#normalverteilung"><span class="toc-section-number">7.5.1</span> Normalverteilung</a></li>
<li><a href="7-5-anhang-kap7.html#student-t-verteilung"><span class="toc-section-number">7.5.2</span> Student t-Verteilung</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="8-inf2.html#inf2"><span class="toc-section-number">8</span> t-Tests</a><ul>
<li><a href="8-1-hypothesentests.html#hypothesentests"><span class="toc-section-number">8.1</span> Hypothesentests</a></li>
<li class="has-sub"><a href="8-2-t-test.html#t-test"><span class="toc-section-number">8.2</span> t-Test</a><ul>
<li><a href="8-2-t-test.html#beiseitiger-t-test"><span class="toc-section-number">8.2.1</span> beiseitiger t-Test</a></li>
<li><a href="8-2-t-test.html#linksseitiger-t-test"><span class="toc-section-number">8.2.2</span> linksseitiger t-Test</a></li>
<li><a href="8-2-t-test.html#rechtsseitiger-t-test"><span class="toc-section-number">8.2.3</span> rechtsseitiger t-Test</a></li>
</ul></li>
<li><a href="8-3-übungen-8.html#übungen-8"><span class="toc-section-number">8.3</span> Übungen 8</a></li>
<li><a href="8-4-profi-übungen-8.html#profi-übungen-8"><span class="toc-section-number">8.4</span> Profi-Übungen 8</a></li>
<li class="has-sub"><a href="8-5-hinweise.html#hinweise"><span class="toc-section-number">8.5</span> Hinweise</a><ul>
<li><a href="8-5-hinweise.html#auswahl-der-in-vollzeit-beschäftigten-befragten"><span class="toc-section-number">8.5.1</span> Auswahl der in Vollzeit beschäftigten Befragten</a></li>
</ul></li>
</ul></li>
<li><a href="9-hypo.html#hypo"><span class="toc-section-number">9</span> Hypothesentests</a></li>
<li><a href="10-export1.html#export1"><span class="toc-section-number">10</span> Ergebnisexport &amp; weitere Tipps</a></li>
<li class="has-sub"><a href="11-adva.html#adva"><span class="toc-section-number">11</span> Fortgeschrittene Themen</a><ul>
<li><a href="11-1-wertelabels.html#wertelabels"><span class="toc-section-number">11.1</span> Wertelabels</a></li>
<li><a href="11-2-sortieren.html#sortieren"><span class="toc-section-number">11.2</span> sortieren</a></li>
<li><a href="11-3-informationen-aus-mehreren-variablen.html#informationen-aus-mehreren-variablen"><span class="toc-section-number">11.3</span> Informationen aus mehreren Variablen</a></li>
<li><a href="11-4-egen.html#egen"><span class="toc-section-number">11.4</span> egen</a></li>
<li><a href="11-5-gruppierte-berechnungen.html#gruppierte-berechnungen"><span class="toc-section-number">11.5</span> gruppierte Berechnungen</a></li>
<li><a href="11-6-sep1.html#sep1"><span class="toc-section-number">11.6</span> Subgruppen-Variablen erstellen mit <code>separate</code></a></li>
<li><a href="11-7-collapse.html#collapse"><span class="toc-section-number">11.7</span> collapse</a></li>
<li><a href="11-8-indikatoren-umdrehen.html#indikatoren-umdrehen"><span class="toc-section-number">11.8</span> Indikatoren umdrehen</a></li>
<li><a href="11-9-informationen-aus-mehreren-datensätzen.html#informationen-aus-mehreren-datensätzen"><span class="toc-section-number">11.9</span> Informationen aus mehreren Datensätzen</a></li>
<li><a href="11-10-arbeiten-mit-textvariablen.html#arbeiten-mit-textvariablen"><span class="toc-section-number">11.10</span> Arbeiten mit Textvariablen</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="anhang-kap7" class="section level2">
<h2><span class="header-section-number">7.5</span> Anhang Kap7</h2>
<div id="normalverteilung" class="section level3">
<h3><span class="header-section-number">7.5.1</span> Normalverteilung</h3>
<p>Eine bedeutende statistische Verteilung in der angewandten Inferenzstatistik ist die Normalverteilung. Sie ist bestimmt durch zwei Parameter: das arithmetische Mittel (<span class="math inline">\(\mu\)</span>) und die Standardabweichung (<span class="math inline">\(\sigma\)</span>) und wird daher auch so dargestellt:</p>
<p><span class="math display">\[N(\mu,\sigma)\]</span>
Die <strong>Standardnormalverteilung</strong> hat einen Mittelwert von 0 und eine Standardabweichung von 1:</p>
<p><span class="math display">\[N(0,1)\]</span></p>
<!-- Die Dichtefunktion der Standardnormalverteilung können wir in Stata mit `dnorm` erzeugen: -->
<p><img src="Stata_Skript_files/figure-html/w8_1-1.png" width="50%" height="50%" style="display: block; margin: auto;" /></p>
<p>Wir können gut erkennen, dass es sich um eine symmetrische Verteilung handelt. Für die Normalverteilung gilt, dass die Fläche unterhalb der Dichtefunktion (also unter der Linie) immer 1 beträgt. Für die Standardnormalverteilung werden die x-Achsenwerte auch als z-Werte bezeichnet. Wenn wir vom Mittelwert aus jeweils bestimmte z-Werte nach rechts und links (also positiv und negativ) als Grenzen für Teilflächen einziehen, ergeben sich verschiedene Standardwerte:</p>
<p><img src="Stata_Skript_files/figure-html/w8_2-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div id="verteilungsfunktion" class="section level4">
<h4><span class="header-section-number">7.5.1.1</span> Verteilungsfunktion</h4>
<p>Die Übersetzung des z-Werts (x-Achsenabschnitts) in die Flächengröße leistet die sog. Verteilungsfunktion. Diese gibt die <em>kumulierte</em> Fläche wieder. Vergleichen Sie die beiden y-Achsen: für <code>z</code> <span class="math inline">\(\rightarrow + \infty\)</span> (“ganz rechts”) nähert sich die Verteilungsfunktion 1 an:</p>
<p><img src="Stata_Skript_files/figure-html/w8_3-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Wir können mit <code>normal</code> berechnen lassen, wie groß jeweils die Fläche <em>links</em> von einem bestimmten Punkt auf der x-Achsen ist. Dazu setzen wir den z-Wert ein:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb355-1"><a href="7-5-anhang-kap7.html#cb355-1"></a><span class="kw">display</span> <span class="fu">normal</span>(-0.674)</span></code></pre></div>
<pre><code>##  . display normal(-0.674)
## .25015566</code></pre>
<p>Noch einmal zusammengefasst: 25% der Verteilung liegen links des z-Werts von -0.674. <code>z = -0.674</code> ist also die 1. Quartilsgrenze für eine Standardnormalverteilung. <span class="math inline">\(\rightarrow\)</span> 75% der Verteilung liegen rechts von <code>z = -0.674</code>.</p>
<p><strong>Warum ist das interessant?</strong> Wir können damit für normalverteilte Merkmale und Kennzahlen (und das sind viele) Aussagen mit Blick auf eine Grundgesamtheit treffen, indem wir den interessierenden Wert <em>standardisieren</em>.</p>
</div>
<div id="standardisierung" class="section level4">
<h4><span class="header-section-number">7.5.1.2</span> Standardisierung</h4>
<p>Ein klassisches Anwendungsbeispiel für eine Normalverteilung ist der Intelligenzquotient. Dessen Skala ist so definiert, dass sie einer Normalverteilung <span class="math inline">\(NV(\mu=100,\sigma = 15)\)</span> entspricht. Betrachten wir Person A mit einem IQ von 130. Wie viel Prozent der IQ-Werte liegen unter einem IQ von 130? Um diese Frage zu beantworten müssen wir den Wert z-Standardisieren entsprechend der folgenden Formel:
<span class="math display">\[z=\frac{x-\mu}{\sigma}\]</span> Also setzen wir ein und erhalten <span class="math inline">\(\frac{130-100}{15} = 2\)</span>:
<img src="Stata_Skript_files/figure-html/unnamed-chunk-86-1.png" width="6400" style="display: block; margin: auto;" /></p>
<p>Diesen z-Wert von 2 können wir nun in die Verteilungsfunktion einsetzen:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb357-1"><a href="7-5-anhang-kap7.html#cb357-1"></a><span class="kw">display</span> <span class="fu">normal</span>(2)</span></code></pre></div>
<pre><code>##  . display normal(2)
## .97724987</code></pre>
<p>97.725% aller IQ-Werte sind also kleiner als 130. Daraus ergibt sich auch: <span class="math inline">\(100\%-97.725\% =\)</span> 2.275% aller IQ-Werte sind <em>größer</em> als 130.</p>
<p>Wir können auch umgekehrt fragen, welcher IQ-Wert nötig ist, um zu den höchsten 1% zu gehören. Dazu formen wir die Standardisierungsformel zu <span class="math inline">\(\mu+z\times\sigma\)</span> um. <span class="math inline">\(\mu\)</span>=100,<span class="math inline">\(\sigma\)</span> = 15 ergeben sich aus der IQ-Definition. Den z-Wert für das 99%-Quantil bekommen wir mit <code>invnormal(.99)</code>:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb359-1"><a href="7-5-anhang-kap7.html#cb359-1"></a><span class="kw">display</span> <span class="fu">invnormal</span>(.99)</span></code></pre></div>
<pre><code>##  . display invnormal(.99)
## 2.3263479</code></pre>
<div class="sourceCode" id="cb361"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb361-1"><a href="7-5-anhang-kap7.html#cb361-1"></a><span class="kw">display</span> 100 + 2.3263479*15 </span></code></pre></div>
<pre><code>##  . display 100 + 2.3263479*15 
## 134.89522</code></pre>
<p>Um beim IQ zu den Top 1% zu gehören, ist ein IQ von mindestens 134.895 nötig.</p>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-87-1.png" width="6400" style="display: block; margin: auto;" /></p>
<p>Welcher IQ ist höchstens unter den niedrigsten 1%?</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb363-1"><a href="7-5-anhang-kap7.html#cb363-1"></a><span class="kw">display</span> <span class="fu">invnormal</span>(.01) </span></code></pre></div>
<pre><code>##  . display invnormal(.01) 
## -2.3263479</code></pre>
<p>Dieser Wert ist negativ weil wir uns links vom Mittelwert befinden!</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb365-1"><a href="7-5-anhang-kap7.html#cb365-1"></a><span class="kw">display</span> 100 + -2.326348*15</span></code></pre></div>
<pre><code>##  . display 100 + -2.326348*15
## 65.10478</code></pre>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-88-1.png" width="6400" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="student-t-verteilung" class="section level3">
<h3><span class="header-section-number">7.5.2</span> Student t-Verteilung</h3>
<p>In der Praxis wird die Standardnormalverteilung aber nur selten genutzt, denn das oben gezeigte Vorgehen setzt voraus, dass die Standardabweichung in der Grundgesamtheit (<span class="math inline">\(\sigma\)</span>) bekannt ist. Dies ist aber in der Regel nicht der Fall. Es ergeben sich zwei Möglichkeiten:</p>
<ul>
<li><p>Bei großen Stichproben kann die Standardabweichung der Stichprobe (<span class="math inline">\(s\)</span>) als Schätzer für <span class="math inline">\(\sigma\)</span> verwendet werden (ab <span class="math inline">\(n\geq30\)</span>)</p></li>
<li><p>Verwendung der t-Verteilung, welche durch Freiheitsgrade die Stichprobengröße berücksichtigt</p></li>
</ul>
<p>Die t-Verteilung ähnelt der Standardnormalverteilung, beide haben einen Mittelwert von <span class="math inline">\(\mu = 0\)</span>. Streng genommen gibt es jedoch nicht eine t-Verteilung, sondern viele - diese unterscheiden sich durch die sogenannten Freiheitsgrade. Dieser wird mit <code>df</code> (“degrees of freedom”) abgekürzt und entspricht der “Stichprobengröße minus 1”: <span class="math inline">\(n-1\)</span>. Im Vergleich zur Standardnormalverteilung hat die t-Verteilung “breitere” Ränder, die sich aber bei steigender Stichprobengröße (höheren <code>df</code>) der Standardnormalverteilung annähern:</p>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-89-1.png" width="100%" style="display: block; margin: auto;" />
Wir können also einfach die t-Verteilung verwenden und die Stichprobengröße angeben - für große Stichproben wird sich das Ergebnis an die Standardnormalverteilung annähern. Bei kleineren Stichproben sind wir auf der sicheren Seite. Im Grundsatz können wir also für alle (annähernd) normalverteilen Merkmale die t-Verteilung verwenden.</p>
<p>Wie für die Standardnormalverteilung bekommen wir mit <code>ttail</code> angegeben, wieviel % der Fläche <em>rechts</em> eines t-Werts (“z-Wert der t-Verteilung”) liegen bei einer bestimmten Zahl von <code>df</code>:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb367-1"><a href="7-5-anhang-kap7.html#cb367-1"></a><span class="kw">display</span> <span class="fu">ttail</span>(2,1)</span></code></pre></div>
<pre><code>##  . display ttail(2,1)
## .21132487</code></pre>
<p>Für die Fläche links davon rechnen wir folglich <code>1-ttail</code>:</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb369-1"><a href="7-5-anhang-kap7.html#cb369-1"></a><span class="kw">display</span> 1- <span class="fu">ttail</span>(2,1)</span></code></pre></div>
<pre><code>##  . display 1- ttail(2,1)
## .78867513</code></pre>
<p>Bei einer Stichprobengröße von 3 (<code>df</code><span class="math inline">\(+1\)</span>) liegen 78.87% links von einem t-Wert = 1.</p>
<div id="t-standardisierung" class="section level4">
<h4><span class="header-section-number">7.5.2.1</span> t-Standardisierung</h4>
<p>Noch einmal zu unserem IQ-Beispiel: stellen wir uns vor, dass für den mittleren IQ (<span class="math inline">\(\bar{IQ}\)</span>=100) und dessen Standardabweichung (<span class="math inline">\(s\)</span>=15) auf einer Stichprobe von <span class="math inline">\(n=15\)</span> beruht. Wir würden uns wieder fragen, wie viel Prozent aller Personen in der Grundgesamtheit wohl einen IQ <span class="math inline">\(\leq\)</span> 130 haben. Zunächst verwenden wir wieder die Standardisierungsformel (diese ändert sich nicht im Vergleich zur Standard-NV):
<span class="math display">\[t=\frac{x-\bar{x}}{s}\]</span>
Also setzen wir ein und erhalten wie oben <span class="math inline">\(\frac{130-100}{15} = 2\)</span>.</p>
<p>Der Hauptunterschied zum Vorgehen bei der Standardnormalverteilung ist jetzt, dass wir anstelle von <code>invnormal</code> jetzt eben <code>1-ttail</code> mit der entsprechenden <code>df=n-1</code> verwenden:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb371-1"><a href="7-5-anhang-kap7.html#cb371-1"></a>dis 1-<span class="fu">ttail</span>(14,2)</span></code></pre></div>
<pre><code>##  . dis 1-ttail(14,2)
## .96735602</code></pre>
<p>Basierend auf einer Stichprobe von 15 Personen mit einem Mittelwert von 100 und einer Standardabweichung von 15 sind also 96.736% aller IQ-Werte kleiner als 130. Daraus ergibt sich auch: <span class="math inline">\(100\%-96.736\% =\)</span> 3.264% aller IQ-Werte sind <em>größer</em> als 130.</p>
<blockquote>
<p>Zum Vergleich: oben - auf Basis der Standard-NV - waren es 97.725%</p>
</blockquote>
<p>Auch hier können wir uns natürlich umgekehrt fragen, wie hoch der IQ sein muss um zu den Top 1% zu gehören. Dazu suchen wir erst mit <code>invttail</code> den entsprechenden t-Wert und setzen dann wieder in die umgeformte Formel <span class="math inline">\(\bar{x}+t\times s\)</span> ein:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb373-1"><a href="7-5-anhang-kap7.html#cb373-1"></a>dis <span class="fu">invttail</span>(14,.99)</span></code></pre></div>
<pre><code>##  . dis invttail(14,.99)
## -2.6244941</code></pre>
<p>Da wir die obere/rechte Grenze suchen, verwenden wir +2.6244941:</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode stata"><code class="sourceCode stata"><span id="cb375-1"><a href="7-5-anhang-kap7.html#cb375-1"></a><span class="kw">display</span> 100 + 2.6244941* 15</span></code></pre></div>
<pre><code>##  . display 100 + 2.6244941* 15
## 139.36741</code></pre>
<p>Basierend auf einer Stichprobe von 15 Personen mit einem Mittelwert von 100 und einer Standardabweichung von 15 ist also ein IQ von 139.367 nötig, um zu den Top 1% zu gehören.</p>
<blockquote>
<p>Zum Vergleich: oben - auf Basis der Standard-NV - waren es 134.895.</p>
</blockquote>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-90-1.png" width="100%" style="display: block; margin: auto;" /></p>

</div>
</div>
</div>
<!-- </div> -->
<p style="text-align: center;">
<a href="7-4-übungen-7.html"><button class="btn btn-default">Previous</button></a>
<a href="8-inf2.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
