<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Regression | GESIS Methodenseminar 2020</title>
  <meta name="description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Regression | GESIS Methodenseminar 2020" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Regression | GESIS Methodenseminar 2020" />
  
  <meta name="twitter:description" content="Dies ist das Begleitskript für die Stata-Übungen zum GESIS Methodenseminar 2020" />
  

<meta name="author" content="Andreas Filser" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="dataviz.html"/>
<link rel="next" href="inf1.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Gesis Methodenseminar</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Herzlich Willkommen!</a></li>
<li class="chapter" data-level="1" data-path="Stata1.html"><a href="Stata1.html"><i class="fa fa-check"></i><b>1</b> Einstieg in Stata</a><ul>
<li class="chapter" data-level="1.1" data-path="Stata1.html"><a href="Stata1.html#taschenrechner"><i class="fa fa-check"></i><b>1.1</b> Taschenrechner</a></li>
<li class="chapter" data-level="1.2" data-path="Stata1.html"><a href="Stata1.html#darstellung-in-diesem-skript"><i class="fa fa-check"></i><b>1.2</b> Darstellung in diesem Skript</a></li>
<li class="chapter" data-level="1.3" data-path="Stata1.html"><a href="Stata1.html#dofile-editor"><i class="fa fa-check"></i><b>1.3</b> DoFile Editor</a></li>
<li class="chapter" data-level="1.4" data-path="Stata1.html"><a href="Stata1.html#datensätze-laden"><i class="fa fa-check"></i><b>1.4</b> Datensätze laden</a></li>
<li class="chapter" data-level="1.5" data-path="Stata1.html"><a href="Stata1.html#überblicksbefehle"><i class="fa fa-check"></i><b>1.5</b> Überblicksbefehle</a></li>
<li class="chapter" data-level="1.6" data-path="Stata1.html"><a href="Stata1.html#if-bedingung---nur-manche-zeilen-ansehen"><i class="fa fa-check"></i><b>1.6</b> if Bedingung - nur manche Zeilen ansehen</a></li>
<li class="chapter" data-level="1.7" data-path="Stata1.html"><a href="Stata1.html#U1"><i class="fa fa-check"></i><b>1.7</b> Übungen</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Stata2.html"><a href="Stata2.html"><i class="fa fa-check"></i><b>2</b> Arbeiten mit Datensätzen in Stata</a><ul>
<li class="chapter" data-level="2.1" data-path="Stata2.html"><a href="Stata2.html#vorab-befehlsstruktur-hilfe"><i class="fa fa-check"></i><b>2.1</b> Vorab: Befehlsstruktur &amp; Hilfe</a></li>
<li class="chapter" data-level="2.2" data-path="Stata2.html"><a href="Stata2.html#auszählen-überblick-erhalten"><i class="fa fa-check"></i><b>2.2</b> Auszählen &amp; Überblick erhalten</a></li>
<li class="chapter" data-level="2.3" data-path="Stata2.html"><a href="Stata2.html#neue-variablen-erstellen"><i class="fa fa-check"></i><b>2.3</b> Neue Variablen erstellen</a></li>
<li class="chapter" data-level="2.4" data-path="Stata2.html"><a href="Stata2.html#gen-ist-gut-kontrolle-ist-besser"><i class="fa fa-check"></i><b>2.4</b> gen ist gut, Kontrolle ist besser</a></li>
<li class="chapter" data-level="2.5" data-path="Stata2.html"><a href="Stata2.html#if-bedingungen"><i class="fa fa-check"></i><b>2.5</b> if Bedingungen</a></li>
<li class="chapter" data-level="2.6" data-path="Stata2.html"><a href="Stata2.html#bestehende-variablen-verändern"><i class="fa fa-check"></i><b>2.6</b> Bestehende Variablen verändern</a></li>
<li class="chapter" data-level="2.7" data-path="Stata2.html"><a href="Stata2.html#keep-drop"><i class="fa fa-check"></i><b>2.7</b> keep &amp; drop</a></li>
<li class="chapter" data-level="2.8" data-path="Stata2.html"><a href="Stata2.html#nochmal-von-vorne-daten-neu-laden"><i class="fa fa-check"></i><b>2.8</b> Nochmal von vorne: Daten neu laden</a></li>
<li class="chapter" data-level="2.9" data-path="Stata2.html"><a href="Stata2.html#speichern"><i class="fa fa-check"></i><b>2.9</b> Speichern</a></li>
<li class="chapter" data-level="2.10" data-path="Stata2.html"><a href="Stata2.html#übungen"><i class="fa fa-check"></i><b>2.10</b> Übungen</a></li>
<li class="chapter" data-level="2.11" data-path="Stata2.html"><a href="Stata2.html#fortgeschrittene-themen"><i class="fa fa-check"></i><b>2.11</b> Fortgeschrittene Themen</a><ul>
<li class="chapter" data-level="2.11.1" data-path="Stata2.html"><a href="Stata2.html#sortieren"><i class="fa fa-check"></i><b>2.11.1</b> sortieren</a></li>
<li class="chapter" data-level="2.11.2" data-path="Stata2.html"><a href="Stata2.html#indikatoren-umdrehen"><i class="fa fa-check"></i><b>2.11.2</b> Indikatoren umdrehen</a></li>
<li class="chapter" data-level="2.11.3" data-path="Stata2.html"><a href="Stata2.html#informationen-aus-mehreren-variablen"><i class="fa fa-check"></i><b>2.11.3</b> Informationen aus mehreren Variablen</a></li>
<li class="chapter" data-level="2.11.4" data-path="Stata2.html"><a href="Stata2.html#informationen-aus-mehreren-datensätzen"><i class="fa fa-check"></i><b>2.11.4</b> Informationen aus mehreren Datensätzen</a></li>
<li class="chapter" data-level="2.11.5" data-path="Stata2.html"><a href="Stata2.html#egen"><i class="fa fa-check"></i><b>2.11.5</b> egen</a></li>
<li class="chapter" data-level="2.11.6" data-path="Stata2.html"><a href="Stata2.html#collapse"><i class="fa fa-check"></i><b>2.11.6</b> collapse</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="desc1.html"><a href="desc1.html"><i class="fa fa-check"></i><b>3</b> Deskriptive Statistik</a></li>
<li class="chapter" data-level="4" data-path="desc2.html"><a href="desc2.html"><i class="fa fa-check"></i><b>4</b> Mehr deskriptive Statistik</a></li>
<li class="chapter" data-level="5" data-path="dataviz.html"><a href="dataviz.html"><i class="fa fa-check"></i><b>5</b> Datenvisualisierung in Stata</a><ul>
<li class="chapter" data-level="5.1" data-path="dataviz.html"><a href="dataviz.html#grafik-syntax-in-stata"><i class="fa fa-check"></i><b>5.1</b> Grafik-Syntax in Stata</a><ul>
<li class="chapter" data-level="5.1.1" data-path="dataviz.html"><a href="dataviz.html#aufbau"><i class="fa fa-check"></i><b>5.1.1</b> Aufbau</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataviz.html"><a href="dataviz.html#twoway"><i class="fa fa-check"></i><b>5.1.2</b> twoway</a></li>
<li class="chapter" data-level="5.1.3" data-path="dataviz.html"><a href="dataviz.html#kombinieren-von-zwei-twoway-grafiken"><i class="fa fa-check"></i><b>5.1.3</b> Kombinieren von zwei twoway-Grafiken</a></li>
<li class="chapter" data-level="5.1.4" data-path="dataviz.html"><a href="dataviz.html#vorlagen"><i class="fa fa-check"></i><b>5.1.4</b> Vorlagen</a></li>
<li class="chapter" data-level="5.1.5" data-path="dataviz.html"><a href="dataviz.html#optionen"><i class="fa fa-check"></i><b>5.1.5</b> Optionen</a></li>
<li class="chapter" data-level="5.1.6" data-path="dataviz.html"><a href="dataviz.html#farben"><i class="fa fa-check"></i><b>5.1.6</b> Farben</a></li>
<li class="chapter" data-level="5.1.7" data-path="dataviz.html"><a href="dataviz.html#subgruppen"><i class="fa fa-check"></i><b>5.1.7</b> Subgruppen</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataviz.html"><a href="dataviz.html#abschließende-beispiele"><i class="fa fa-check"></i><b>5.2</b> Abschließende Beispiele</a></li>
<li class="chapter" data-level="5.3" data-path="dataviz.html"><a href="dataviz.html#bevölkerungspyramide"><i class="fa fa-check"></i><b>5.3</b> Bevölkerungspyramide</a></li>
<li class="chapter" data-level="5.4" data-path="dataviz.html"><a href="dataviz.html#abschließende-bemerkungen"><i class="fa fa-check"></i><b>5.4</b> Abschließende Bemerkungen</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lin-reg.html"><a href="lin-reg.html"><i class="fa fa-check"></i><b>6</b> Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="lin-reg.html"><a href="lin-reg.html#aufgaben"><i class="fa fa-check"></i><b>6.1</b> Aufgaben</a><ul>
<li class="chapter" data-level="6.1.1" data-path="lin-reg.html"><a href="lin-reg.html#aufgabe-1"><i class="fa fa-check"></i><b>6.1.1</b> Aufgabe 1</a></li>
<li class="chapter" data-level="6.1.2" data-path="lin-reg.html"><a href="lin-reg.html#aufgabe-2"><i class="fa fa-check"></i><b>6.1.2</b> Aufgabe 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="inf1.html"><a href="inf1.html"><i class="fa fa-check"></i><b>7</b> Inferenzstatistik I</a></li>
<li class="chapter" data-level="8" data-path="inf2.html"><a href="inf2.html"><i class="fa fa-check"></i><b>8</b> Inferenzstatistik II</a></li>
<li class="chapter" data-level="9" data-path="hypo.html"><a href="hypo.html"><i class="fa fa-check"></i><b>9</b> Hypothesentests</a></li>
<li class="chapter" data-level="10" data-path="export1.html"><a href="export1.html"><i class="fa fa-check"></i><b>10</b> Ergebnisexport &amp; weitere Tipps</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GESIS Methodenseminar 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lin_reg" class="section level1">
<h1><span class="header-section-number">6</span> Regression</h1>
<p>Zum Einstieg betrachten wir zunächst einen (fiktiven) Datensatz mit lediglich 4 Fällen. Mit dem <code>data.frame</code> Befehl können wir einen Datensatz erstellen. Unserer hat zunächst lediglich zwei Variablen: var1 und var2</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="lin-reg.html#cb1-1"></a>df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">var1 =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">7</span>,<span class="dv">8</span>),</span>
<span id="cb1-2"><a href="lin-reg.html#cb1-2"></a>                 <span class="dt">var2 =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">6</span>))</span>
<span id="cb1-3"><a href="lin-reg.html#cb1-3"></a>df</span></code></pre></div>
<pre><code>##   var1 var2
## 1    1    2
## 2    2    4
## 3    7    7
## 4    8    6</code></pre>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-2-1.png" width="240" style="display: block; margin: auto;" /></p>
<p>Wie lassen sich diese Daten beschreiben? Wie können wir einen (möglichen) Zusammenhang zwischen <code>var1</code> und <code>var2</code> beschreiben?</p>
<p>Eine Möglichkeit, die wir Sie in Statistik1 kennen gelernt haben, war das arithmetische Mittel. Dieses können wir mit <code>mean</code> zB für <code>var2</code> berechnen. Diesen Wert fürgen wir als neue Spalte “mean” in den Datensatz df ein. Anschließend können wir das artih. Mittel einzeichnen.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="lin-reg.html#cb3-1"></a>df<span class="op">$</span>mean &lt;-<span class="st"> </span><span class="kw">mean</span>(df<span class="op">$</span>var2)</span>
<span id="cb3-2"><a href="lin-reg.html#cb3-2"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean
## 1    1    2 4.75
## 2    2    4 4.75
## 3    7    7 4.75
## 4    8    6 4.75</code></pre>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-4-1.png" width="288" style="display: block; margin: auto;" />
Müssten wir eine Prognose für die Werte von <code>var2</code> abgeben, wäre das arith. Mittel eine gute Wahl. Die <strong>vorhergesagten Werte</strong> werden jeweils auf der Linie für das arith. Mittel liegen.</p>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-5-1.png" width="288" style="display: block; margin: auto;" />
Allerdings liegen wir mit dem arith. Mittel dann immer auch Stück daneben. Diese Abweichung zwischen dem tatsächlichen und dem vorhergesagten Wert wird als <strong>Residuum</strong> bezeichnet, in unserem Beispiel ist das jeweils die Differenz zwischen <code>var2</code> und <code>mean</code>:
<span class="math display">\[Residuum = beobachteter\, Wert \; - \; vorhergesagter\,Wert\]</span>
Als Formel wird das in der Regel wie folgt dargestellt:
<span class="math display">\[\epsilon_{\text{i}} = \text{y}_{i} - \hat{\text{y}}_{i}\]</span></p>
<p>Wir können also die Residuem als Differenz zwischen <code>var2</code> und <code>mean</code> berechnen und in <code>df</code> ablegen:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="lin-reg.html#cb5-1"></a>df<span class="op">$</span>m_residuen &lt;-<span class="st"> </span>df<span class="op">$</span>var2 <span class="op">-</span><span class="st"> </span>df<span class="op">$</span>mean</span>
<span id="cb5-2"><a href="lin-reg.html#cb5-2"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen
## 1    1    2 4.75      -2.75
## 2    2    4 4.75      -0.75
## 3    7    7 4.75       2.25
## 4    8    6 4.75       1.25</code></pre>
<p><img src="Stata_Skript_files/figure-html/unnamed-chunk-7-1.png" width="288" style="display: block; margin: auto;" /></p>
<p><em>Was bedeutet also ein negativer oder ein positiver Wert für das Residuum?</em></p>
<p>Die horizontale Linie für das arithm. Mittel ist aber sehr deutlich nicht die beste Methode, um die Werte für <code>var2</code> vorherzusagen. In der Graphik können wir deutlich sehen, dass die Werte “weiter links”, also mit geringeren Werten für <code>var1</code>, auch geringere Werte für <code>var2</code> aufweisen. Wir könnten also unseren Vorhersagefehler bzw. das <em>Residuum</em> minimieren indem wir die Linie drehen. Die Idee der Regressionsanalyse ist es dabei, die Residuuen zu minimieren. Was würde aber passieren wenn wir die Residuen aus der Mittelwertsvorhersage aufsummieren, um Sie dann zu minimieren?</p>
<p>Mit <code>sum</code> können wir die Summe für eine Variable bilden:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="lin-reg.html#cb7-1"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen
## 1    1    2 4.75      -2.75
## 2    2    4 4.75      -0.75
## 3    7    7 4.75       2.25
## 4    8    6 4.75       1.25</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="lin-reg.html#cb9-1"></a><span class="kw">sum</span>(df<span class="op">$</span>m_residuen)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="lin-reg.html#cb11-1"></a><span class="kw">sum</span>(df<span class="op">$</span>m_residuen[df<span class="op">$</span>m_residuen<span class="op">&lt;</span><span class="dv">0</span>])</span></code></pre></div>
<pre><code>## [1] -3.5</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="lin-reg.html#cb13-1"></a><span class="kw">sum</span>(df<span class="op">$</span>m_residuen[df<span class="op">$</span>m_residuen<span class="op">&gt;</span><span class="dv">0</span>])</span></code></pre></div>
<pre><code>## [1] 3.5</code></pre>
<p><strong>Die Summe der Resiuden auf Basis des arith. Mittels ist immer Null!</strong><br />
Anders formuliert: die gestrichelten Linien nach oben sind in Summe genauso lang wie gestrichelten Linien nach unten.

Die Lösung ist die Residuen zu quadrieren. So ergibt sich eine Kennzahl, die wir minimieren können:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="lin-reg.html#cb15-1"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen
## 1    1    2 4.75      -2.75
## 2    2    4 4.75      -0.75
## 3    7    7 4.75       2.25
## 4    8    6 4.75       1.25</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="lin-reg.html#cb17-1"></a>df<span class="op">$</span>m_residuen2 &lt;-<span class="st"> </span>df<span class="op">$</span>m_residuen<span class="op">^</span><span class="dv">2</span> </span>
<span id="cb17-2"><a href="lin-reg.html#cb17-2"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen m_residuen2
## 1    1    2 4.75      -2.75      7.5625
## 2    2    4 4.75      -0.75      0.5625
## 3    7    7 4.75       2.25      5.0625
## 4    8    6 4.75       1.25      1.5625</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="lin-reg.html#cb19-1"></a><span class="kw">sum</span>(df<span class="op">$</span>m_residuen2)</span></code></pre></div>
<pre><code>## [1] 14.75</code></pre>
<p>Die Minimierung erledigt <code>lm()</code> für uns. Hier geben wir das Merkmal an, das auf der y-Achse liegt (die <em>abhängige</em> Variable) und nach einer <code>~</code> das Merkmal für die x-Achse (<em>unabhängige</em> Variable). Die Interpretation des Ergebnisses wird uns die kommenden Wochen beschäftigen. Für heute ist wichtig, dass ein positiver Wert unter <code>var1</code> bedeutet, dass unsere Gerade von links nach rechts ansteigt und ein negativer eine fallende Linie bedeuten würde. Der Wert unter <code>var1</code> gibt an, um <em>wieviel sich die Gerade pro “Schritt nach rechts” nach oben/unten verändert</em>. Die Gerade steigt also pro Einheit von <code>var1</code> um 0.5810811. Die Ergebnisse können wir unter <code>m1</code> ablegen.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="lin-reg.html#cb21-1"></a><span class="kw">lm</span>(var2<span class="op">~</span><span class="st"> </span>var1, <span class="dt">data =</span> df)  </span>
<span id="cb21-2"><a href="lin-reg.html#cb21-2"></a><span class="co">## </span></span>
<span id="cb21-3"><a href="lin-reg.html#cb21-3"></a><span class="co">## Call:</span></span>
<span id="cb21-4"><a href="lin-reg.html#cb21-4"></a><span class="co">## lm(formula = var2 ~ var1, data = df)</span></span>
<span id="cb21-5"><a href="lin-reg.html#cb21-5"></a><span class="co">## </span></span>
<span id="cb21-6"><a href="lin-reg.html#cb21-6"></a><span class="co">## Coefficients:</span></span>
<span id="cb21-7"><a href="lin-reg.html#cb21-7"></a><span class="co">## (Intercept)         var1  </span></span>
<span id="cb21-8"><a href="lin-reg.html#cb21-8"></a><span class="co">##      2.1351       0.5811</span></span>
<span id="cb21-9"><a href="lin-reg.html#cb21-9"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(var2<span class="op">~</span><span class="st"> </span>var1, <span class="dt">data =</span> df)  </span></code></pre></div>
<p>In unserer Grafik sieht diese Gerade so aus:
<img src="Stata_Skript_files/figure-html/unnamed-chunk-12-1.png" width="240" style="display: block; margin: auto;" /></p>
<p>In welcher Hinsicht ist die Gerade nun eine Verbesserung gegenüber dem <code>mean</code>? Wir können uns für eine Einschätzung die Residuen ansehen. Für den Punkt ganz links hatte wir vorhin berechnet, dass das Residuum auf Basis des arithm. Mittels (also die Distanz zum orangen Punkt auf der gestrichelten Linie) <code>2-4.75 = -2.75</code> beträgt:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="lin-reg.html#cb22-1"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen m_residuen2
## 1    1    2 4.75      -2.75      7.5625
## 2    2    4 4.75      -0.75      0.5625
## 3    7    7 4.75       2.25      5.0625
## 4    8    6 4.75       1.25      1.5625</code></pre>
<p>Wie hoch ist nun der vorhergesagte Wert auf Basis der blauen Gerade? Sehen wir uns der Ergebnis aus <code>lm(var2~ var1, data = df)</code>, das wir unter <code>m1</code> nochmal an, hier finden sich unter <code>$fitted.values</code> die vorhergesagten Werte von <code>lm()</code>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="lin-reg.html#cb24-1"></a>m1<span class="op">$</span>fitted.values</span></code></pre></div>
<pre><code>##        1        2        3        4 
## 2.716216 3.297297 6.202703 6.783784</code></pre>
<p>Diese vohergesagten Werte entsprechen einfach der Summe aus dem Wert unter <code>Intercept</code> und dem Wert unter <code>var1</code> multipliziert mit dem jeweiligen Wert für <code>var1</code>.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="lin-reg.html#cb26-1"></a>m1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = var2 ~ var1, data = df)
## 
## Coefficients:
## (Intercept)         var1  
##      2.1351       0.5811</code></pre>
<p>Für die erste Zeile aus <code>df</code> ergibt sich also <code>m1</code> folgender vorhergesagter Wert: <code>2.1351+0.5811*1=</code>2.7162</p>
<p>Die Werte unter <code>fitted.values</code> folgen der Reihenfolge im Datensatz, sodass wir sie einfach als neue Spalte in <code>df</code> ablegen können:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="lin-reg.html#cb28-1"></a>df<span class="op">$</span>lm_vorhersagen &lt;-<span class="st"> </span>m1<span class="op">$</span>fitted.values</span>
<span id="cb28-2"><a href="lin-reg.html#cb28-2"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen m_residuen2 lm_vorhersagen
## 1    1    2 4.75      -2.75      7.5625       2.716216
## 2    2    4 4.75      -0.75      0.5625       3.297297
## 3    7    7 4.75       2.25      5.0625       6.202703
## 4    8    6 4.75       1.25      1.5625       6.783784</code></pre>
<p>Die Grafik zeigt wie Vorhersagen auf Basis von <code>m1</code> aussehen: Sie entsprechen den Werten auf der blauen Geraden (der sog. Regressionsgeraden) an den jeweiligen Stellen für <code>var1</code>.
<img src="Stata_Skript_files/figure-html/unnamed-chunk-17-1.png" width="288" style="display: block; margin: auto;" />
Wir können erkennen, dass die hellblauen Punkte (also die Vorhersagen von <code>m1</code>) deutlich näher an den tatsächlichen Punkten liegen als die orangen Vorhersagen auf Basis des <code>mean</code>. Trotzdem sind auch die hellblauen Punkte nicht deckungsgleich mit den tatsächlchen Werten. Es gibt also auch hier wieder Residuen. Wir können diese per Hand berechnen als Differenz zwischen dem tatsächlichen und dem vorhergesagten Wert:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="lin-reg.html#cb30-1"></a>df<span class="op">$</span>var2 <span class="op">-</span><span class="st"> </span>df<span class="op">$</span>lm_vorhersagen</span></code></pre></div>
<pre><code>## [1] -0.7162162  0.7027027  0.7972973 -0.7837838</code></pre>
<p>Oder wir können Sie unter <code>m1$residuals</code> aufrufen:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="lin-reg.html#cb32-1"></a>m1<span class="op">$</span>residuals</span></code></pre></div>
<pre><code>##          1          2          3          4 
## -0.7162162  0.7027027  0.7972973 -0.7837838</code></pre>
<p>Auch die Residuen für <code>lm</code> können wir in <code>df</code> ablegen:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="lin-reg.html#cb34-1"></a>df<span class="op">$</span>lm_residuen &lt;-<span class="st"> </span>m1<span class="op">$</span>residuals</span>
<span id="cb34-2"><a href="lin-reg.html#cb34-2"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen m_residuen2 lm_vorhersagen lm_residuen
## 1    1    2 4.75      -2.75      7.5625       2.716216  -0.7162162
## 2    2    4 4.75      -0.75      0.5625       3.297297   0.7027027
## 3    7    7 4.75       2.25      5.0625       6.202703   0.7972973
## 4    8    6 4.75       1.25      1.5625       6.783784  -0.7837838</code></pre>
<p>Hier sind die Residuen für <code>lm</code> hellblau eingezeichnet:
<img src="Stata_Skript_files/figure-html/unnamed-chunk-21-1.png" width="264" style="display: block; margin: auto;" />
<em>Wie groß ist die Summe der Residuen für <code>lm</code>?</em></p>
<p>Um zu beurteilen, um wieviel besser unsere Gerade aus <code>lm()</code> die Werte vorhersagen kann als der <code>mean</code> können wir die Summe der quadrierten Residuen vergleichen:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="lin-reg.html#cb36-1"></a>df<span class="op">$</span>lm_residuen2 &lt;-<span class="st"> </span>df<span class="op">$</span>lm_residuen<span class="op">^</span><span class="dv">2</span></span>
<span id="cb36-2"><a href="lin-reg.html#cb36-2"></a>df</span></code></pre></div>
<pre><code>##   var1 var2 mean m_residuen m_residuen2 lm_vorhersagen lm_residuen lm_residuen2
## 1    1    2 4.75      -2.75      7.5625       2.716216  -0.7162162    0.5129657
## 2    2    4 4.75      -0.75      0.5625       3.297297   0.7027027    0.4937911
## 3    7    7 4.75       2.25      5.0625       6.202703   0.7972973    0.6356830
## 4    8    6 4.75       1.25      1.5625       6.783784  -0.7837838    0.6143170</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="lin-reg.html#cb38-1"></a><span class="kw">sum</span>(df<span class="op">$</span>m_residuen2)</span></code></pre></div>
<pre><code>## [1] 14.75</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="lin-reg.html#cb40-1"></a><span class="kw">sum</span>(df<span class="op">$</span>lm_residuen2)</span></code></pre></div>
<pre><code>## [1] 2.256757</code></pre>
<p>Zum Beispiel können wir uns fragen, um wieviel sich die Summe der quadrierten Residuen verringert wenn wir statt des <code>mean</code> unser <code>lm</code>-Modell verwenden:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="lin-reg.html#cb42-1"></a><span class="kw">sum</span>(df<span class="op">$</span>m_residuen2)<span class="op">-</span><span class="kw">sum</span>(df<span class="op">$</span>lm_residuen2)</span></code></pre></div>
<pre><code>## [1] 12.49324</code></pre>
<p>Wenn wir diese Veränderung ins Verhältnis mit dem “Ausgangswert”, also den Residuen aus der Mittelwertregel setzen, dann erhalten wir das <span class="math inline">\(R^{2}\)</span> für unser <code>lm()</code>-Modell. Dieses gibt die prozentuale Verringerung der Residuen durch das <code>lm()</code>-Modell im Vergleich zur Mittelwertregel an:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="lin-reg.html#cb44-1"></a>( <span class="kw">sum</span>(df<span class="op">$</span>m_residuen2)<span class="op">-</span><span class="kw">sum</span>(df<span class="op">$</span>lm_residuen2) )<span class="op">/</span><span class="kw">sum</span>(df<span class="op">$</span>m_residuen2)</span></code></pre></div>
<pre><code>## [1] 0.8469995</code></pre>
<p>Unser <code>lm</code>-Modell kann also 84,7% der Streuung um den Mittelwert erklären.</p>
<div id="aufgaben" class="section level2">
<h2><span class="header-section-number">6.1</span> Aufgaben</h2>
<div id="aufgabe-1" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Aufgabe 1</h3>
<p>Erstellen Sie wie folgt einen Beispieldatensatz (Sie können aber gerne auch eigene, andere Werte verwenden)</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="lin-reg.html#cb46-1"></a>df2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">var1 =</span> <span class="kw">c</span>(<span class="dv">12</span>,<span class="dv">10</span>,<span class="dv">24</span>,<span class="dv">28</span>,<span class="dv">23</span>) ,</span>
<span id="cb46-2"><a href="lin-reg.html#cb46-2"></a>                  <span class="dt">var2 =</span> <span class="kw">c</span>(<span class="dv">17</span>,<span class="dv">16</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">8</span>))</span></code></pre></div>
<ul>
<li>Berechnen Sie das arithm. Mittel für <code>var2</code>!</li>
<li>Legen Sie das arithm. Mittel als neue Variable im Datensatz <code>df2</code> ab (siehe S.1)</li>
<li>Berechnen Sie die Residuen für die Mittelwertsregel - wie groß ist die Abweichung vom arith. Mittel für die einzelnen Beobachtungen für <code>var2</code>?</li>
<li>Legen Sie die Residuen der Mittelwertsregel in <code>df2</code> ab</li>
<li>Wie groß ist die Summe der Resiuden, wenn Sie alle Werte zusammen zählen?</li>
<li>Erstellen Sie ein Objekt <code>m2</code> mit einem linearen Regressionsmodell (<code>lm</code>) mit <code>var2</code> als abhängiger und <code>var1</code> als unabhängiger Variable!</li>
<li>Betrachten Sie Ergebnisse <code>m2</code> - was können Sie erkennen? Besteht ein positiver oder negativer Zusammenhang zwischen <code>var1</code> und <code>var2</code>?</li>
<li>Erstellen Sie neue Variablen in <code>df2</code> für die vorhergesagten Werte und die Residuen aus dem Regressionsmodell <code>m2</code></li>
<li>Wie hoch ist die Summe der Residuen aus <code>m2</code>? Wie hoch ist die Summe der quadrierten Residuen für <code>m2</code>?</li>
<li>Berechnen Sie die Differenz zwischen den quadrierten Residuen der Mittelwertregel und den quadrierten Residuen für <code>m2</code>. Berechnen Sie das <span class="math inline">\(R^2\)</span> für <code>m2</code>!</li>
</ul>
</div>
<div id="aufgabe-2" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Aufgabe 2</h3>
<p>Dieses Prinzip funktioniert natürlich genauso für größere Datensätze, zum Beispiel den Allbus 2016. Untersuchen Sie den Zusammenhang zwischen Alter (<code>age</code>) und dem Einkommen (<code>inc</code>) der weiblichen, in Vollzeit erwerbstätigen Befragten!</p>
<ul>
<li>Lesen Sie den Allbus-Datensatz wie bekannt ein. Hier nochmal zu Erinnerung das Vorgehen:</li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="lin-reg.html#cb47-1"></a><span class="co"># Arbeitsverzeichnis in den Ordner mit dem Datensatz setzen:</span></span>
<span id="cb47-2"><a href="lin-reg.html#cb47-2"></a><span class="kw">setwd</span>(<span class="st">&quot;C:/Lehre&quot;</span>) </span>
<span id="cb47-3"><a href="lin-reg.html#cb47-3"></a>a16 &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;allbus2016.csv&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="dt">header =</span> T) <span class="co"># einlesen</span></span></code></pre></div>
<p>Zunächst müssen wir dann die Missings mit <code>NA</code> überschreiben:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="lin-reg.html#cb48-1"></a>a16<span class="op">$</span>age[a16<span class="op">$</span>age<span class="op">&lt;</span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb48-2"><a href="lin-reg.html#cb48-2"></a>a16<span class="op">$</span>inc[a16<span class="op">$</span>inc<span class="op">&lt;</span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></span></code></pre></div>
<p>Mit <code>na.omit</code> können wir dann all die Beobachtungen auswählen, für <code>age</code> und <code>inc</code> nicht Missing sind:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="lin-reg.html#cb49-1"></a>a16 &lt;-<span class="st"> </span><span class="kw">na.omit</span>(a16)</span></code></pre></div>
<ul>
<li>Mit folgendem Befehl können Sie ein Teildatenset <code>a16f</code> erstellen, das nur in Vollzeit erwerbstätige Frauen enthält:</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="lin-reg.html#cb50-1"></a>a16f &lt;-<span class="st"> </span>a16[a16<span class="op">$</span>sex <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">&amp;</span><span class="st"> </span>a16<span class="op">$</span>work <span class="op">==</span><span class="st"> </span><span class="dv">1</span>,] <span class="co"># base R</span></span>
<span id="cb50-2"><a href="lin-reg.html#cb50-2"></a>a16f &lt;-<span class="st"> </span><span class="kw">filter</span>(a16, sex <span class="op">==</span><span class="st"> </span><span class="dv">2</span>, work <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co"># dplyr</span></span></code></pre></div>
<p>Für die Analyse sind nur die Variablen <code>age</code> und <code>inc</code> wichtig, also können wir den Datensatz auf diese beiden Variablen reduzieren:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="lin-reg.html#cb51-1"></a>a16f &lt;-<span class="st"> </span>a16f[,<span class="kw">c</span>(<span class="st">&quot;age&quot;</span>,<span class="st">&quot;inc&quot;</span>)] <span class="co"># base R</span></span>
<span id="cb51-2"><a href="lin-reg.html#cb51-2"></a>a16f &lt;-<span class="st"> </span><span class="kw">select</span>(a16f, age, inc) <span class="co"># dplyr</span></span></code></pre></div>
<p>Mit <code>head</code> können wir uns die ersten Zeilen des Datensatzes anzeigen lassen oder mit <code>View()</code> den gesamten Datensatz ansehen:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="lin-reg.html#cb52-1"></a><span class="kw">head</span>(a16f)</span>
<span id="cb52-2"><a href="lin-reg.html#cb52-2"></a><span class="kw">View</span>(a16f)</span></code></pre></div>
<ul>
<li>Berechnen Sie das arithm. Mittel für das Einkommen</li>
<li>Legen Sie das arithm. Mittel als neue Variable im Datensatz ab (siehe S.1)</li>
<li>Berechnen Sie die Residuen für die Mittelwertregel!</li>
<li>Wie groß ist die Summe der Residuen, wenn Sie alle Werte zusammen zählen?</li>
<li>Erstellen Sie ein Objekt <code>m3</code> mit einem linearen Regressionsmodell (<code>lm</code>) mit dem Einkommen (<code>inc</code>) als abhängiger und dem Alter (<code>age</code>) der Frauen als unabhängiger Variable!</li>
<li>Welche Richtung für die Regressionsgerade können Sie erkennen?</li>
<li>Erstellen Sie neue Variablen in <code>a16f</code> für die vorhergesagten Werte und die Residuen aus dem Regressionsmodell <code>m3</code></li>
<li>Wie hoch ist die Summe der quadrierten Residuen aus <code>m3</code>?</li>
<li>Berechnen Sie das <span class="math inline">\(R^2\)</span> für <code>m3</code>!</li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dataviz.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inf1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
